// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/character_soviet_overcoat";
	a[1] = "xmodel/character_soviet_overcoat2";
	a[2] = "xmodel/character_soviet_tunic";
	a[3] = "xmodel/character_soviet_coat";
	return a;
}
