// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/character_us_wet_ranger_pvt_a_low";
	a[1] = "xmodel/character_us_wet_ranger_pvt_b_low";
	a[2] = "xmodel/character_us_wet_ranger_pvt_c_low";
	a[3] = "xmodel/character_us_wet_ranger_pvt_d_low";
	return a;
}
