// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/character_us_ranger_pvt_a";
	a[1] = "xmodel/character_us_ranger_pvt_b";
	a[2] = "xmodel/character_us_ranger_pvt_c";
	a[3] = "xmodel/character_us_ranger_pvt_d";
	return a;
}
