// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_us_ranger_frank";
	a[1] = "xmodel/head_us_ranger_david";
	a[2] = "xmodel/head_us_ranger_mo";
	a[3] = "xmodel/head_us_ranger_wolf";
	return a;
}
