// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_german_normandy_christoph";
	a[1] = "xmodel/head_german_normandy_eric";
	a[2] = "xmodel/head_german_normandy_josh";
	a[3] = "xmodel/head_german_normandy_ericp";
	return a;
}
