// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/head_us_ranger_frank_low";
	a[1] = "xmodel/head_us_ranger_david_low";
	a[2] = "xmodel/head_us_ranger_mo_low";
	a[3] = "xmodel/head_us_ranger_wolf_low";
	return a;
}
