// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/playerbody_british_normandy01";
	a[1] = "xmodel/playerbody_british_normandy02";
	a[2] = "xmodel/playerbody_british_normandy03";
	a[3] = "xmodel/playerbody_british_normandy04";
	return a;
}
