// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/playerbody_american_normandy01";
	a[1] = "xmodel/playerbody_american_normandy02";
	a[2] = "xmodel/playerbody_american_normandy03";
	a[3] = "xmodel/playerbody_american_normandy04";
	a[4] = "xmodel/playerbody_american_normandy05";
	a[5] = "xmodel/playerbody_american_normandy06";
	a[6] = "xmodel/playerbody_american_normandy07";
	a[7] = "xmodel/playerbody_american_normandy08";
	return a;
}
