// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "xmodel/helmet_russian_trench_a_hat";
	a[1] = "xmodel/helmet_russian_trench_b_hat";
	a[2] = "xmodel/helmet_russian_trench_c_hat";
	return a;
}
