// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	//common_scripts\utility::add_destructible_type_function( "dest_cover_barrier_fusion_truck_01_cheap_scrptdst", destructible_scripts\dest_cover_barrier_fusion_truck_01_cheap_scrptdst::main );
	common_scripts\utility::add_destructible_type_function( "computer_01_destp", destructible_scripts\computer_01_destp::main );
	common_scripts\utility::add_destructible_type_function( "container_plastic_72x48x44_01_destp", destructible_scripts\container_plastic_72x48x44_01_destp::main );
	common_scripts\utility::add_destructible_type_function( "container_plastic_72x56x48_01_destp", destructible_scripts\container_plastic_72x56x48_01_destp::main );
	common_scripts\utility::add_destructible_type_function( "container_plastic_beige_med_01_destp", destructible_scripts\container_plastic_beige_med_01_destp::main );
	common_scripts\utility::add_destructible_type_function( "powerbox_112x64_01_green_destp", destructible_scripts\powerbox_112x64_01_green_destp::main );
	destructible_scripts\computer_01_destp::main();
	destructible_scripts\container_plastic_72x48x44_01_destp::main();
	destructible_scripts\container_plastic_72x56x48_01_destp::main();
	destructible_scripts\container_plastic_beige_med_01_destp::main();
	destructible_scripts\powerbox_112x64_01_green_destp::main();
	vehicle_scripts\_cover_drone::main( "vehicle_mobile_cover", undefined, "script_vehicle_cover_drone" );
	vehicle_scripts\_f15::main( "vehicle_f15", undefined, "script_vehicle_f15" );
	vehicle_scripts\_gaz_dshk::main( "vehicle_gaz_tigr_base", undefined, "script_vehicle_gaz_tigr_turret" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly", undefined, "script_vehicle_mi17_woodland_fly" );
	vehicle_scripts\_pdrone::main( "vehicle_pdrone", undefined, "script_vehicle_pdrone" );
	vehicle_scripts\_pdrone::main( "vehicle_atlas_assault_drone_large", undefined, "script_vehicle_pdrone_atlas_large" );
	vehicle_scripts\_pdrone::main( "vehicle_pdrone_kva", undefined, "script_vehicle_pdrone_kva" );
	vehicle_scripts\_walker_tank::main( "vehicle_walker_tank", undefined, "script_vehicle_walker_tank" );
	vehicle_scripts\_x4walker_wheels::main( "vehicle_x4walker_wheels", undefined, "script_vehicle_x4walker_wheels" );
	vehicle_scripts\_x4walker_wheels_turret::main( "vehicle_npc_x4walkerSplit_wheels", undefined, "script_vehicle_x4walker_wheels_turret" );
	vehicle_scripts\_xh9_warbird::main( "vehicle_xh9_warbird", undefined, "script_vehicle_xh9_warbird" );
	vehicle_scripts\_xh9_warbird::main( "vehicle_xh9_warbird_low", undefined, "script_vehicle_xh9_warbird_low" );
	vehicle_scripts\_xh9_warbird::main( "vehicle_xh9_warbird_low", undefined, "script_vehicle_xh9_warbird_low_no_turret_no_zipline" );
	vehicle_scripts\_xh9_warbird::main( "vehicle_xh9_warbird", undefined, "script_vehicle_xh9_warbird_no_turret" );
	vehicle_scripts\_xh9_warbird::main( "vehicle_xh9_warbird_stealth", undefined, "script_vehicle_xh9_warbird_stealth" );
}
