// the REGION shader is generated by the map editor on temporary
// brushes around a selected area for testing parts of maps

textures/common/nodraw_notsolid
{
	//qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}
textures/common/vehicleclip
{
	qer_trans 0.3
	surfaceparm metal
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm vehicleclip
}
textures/common/aitrig
{
	qer_trans 0.32
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/spawner_trigger
{
	qer_trans 0.32
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/return_spawner_trigger
{
	qer_trans 0.32
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/blackish
{
     {
	map textures/common/blackish
	rgbGen identity
    nextbundle
	map $lightmap
     }
}

textures/common/clipmissile
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
	surfaceparm clipmissile
	surfaceparm canshootclip
}

textures/common/nodraw
{
	//qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm vehicleclip
	surfaceparm trans
//	surfaceparm clipmissile  //removed so you can throw grenades through masked textures.
//	surfaceparm canshootclip  //removed cause no one knows why it was here in the first place -z
}

textures/common/nodraw_decal
{
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm noncolliding
	surfaceparm trans
}

textures/common/water
{
	qer_trans 0.5
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm water
}

textures/REGION
{
	surfaceparm nolightmap
}

textures/common/nodrop
{
	qer_trans 0.5
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm nodrop
	cull disable
}

textures/common/clipweap
{
	qer_trans 0.3
	//surfaceparm playerclip
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/clipfull
{
	qer_trans 0.3
	surfaceparm clipshot
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm canshootclip
}

textures/common/clipfoliage
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm foliage
	surfaceparm ai_nosight
}

textures/common/clip_nosight
{
	qer_trans 0.3
	surfaceparm wood
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}

textures/common/clip_nosight_nothing
{
	qer_trans 0.3
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}



textures/common/clip_nosight_metal
{
	qer_trans 0.3
	surfaceparm metal
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}

textures/common/clip_nosight_dirt
{
	qer_trans 0.3
	surfaceparm dirt
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}

textures/common/clip_nosight_rock
{
	qer_trans 0.3
	surfaceparm rock
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}


textures/common/clip_nosight_novehicle  //for tanks.. should clip player running into tanks
{
	qer_editorimage textures/common/clip_nosight.tga
	qer_trans 0.3
	surfaceparm metal
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm ai_nosight
	surfaceparm itemclip
	surfaceparm canshootclip
}


textures/common/nosight_noclip
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm ai_nosight
}

textures/common/clip
{
	qer_trans 0.3
	surfaceparm noimpact
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm monsterclip
	surfaceparm vehicleclip
	//surfaceparm canshootclip
}

textures/common/clipplayer
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
}

textures/common/clip_metal
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm clipmissile
	surfaceparm monsterclip
	surfaceparm trans
	surfaceparm metal
	surfaceparm vehicleclip
	surfaceparm itemclip
	surfaceparm canshootclip
}



textures/common/clipmonster
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm monsterclip
}

textures/common/ladder
{
	qer_trans 0.3
	//surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm ladder
}

textures/common/ladder_wood
{
	qer_trans 0.3
	surfaceparm wood
	//surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm ladder
}

textures/common/hint
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm noimpact
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/skip
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/origin
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm origin
}

textures/common/areaportal
{
	surfaceparm areaportal
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/trigger
{
	qer_trans 0.5
	surfaceparm nodraw
}

textures/common/caulk
{
	surfaceparm nodraw
	surfaceparm castshadow
	surfaceparm nomarks
}

textures/common/occluder
{
	qer_trans 0.5
	surfaceparm occluder
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/portal
{
	qer_trans 0.5
	surfaceparm portal
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm hint
}

textures/common/portalnodraw
{
	qer_trans 0.5
	qer_drawtoggle
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/cushion
{
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/nodrawnonsolid
{
	surfaceparm nodraw
	surfaceparm nonsolid
}

textures/common/mirror
{
	surfaceparm nolightmap
	portal
	{
		map $whiteimage
		alphaGen const 0.1f
		rgbGen constLighting ( 0.4 0.8 0.64 )
		blendFunc blend
		depthWrite
	}
}

textures/common/shadow
{
	surfaceparm nodraw
	surfaceparm castshadow
	surfaceparm nomarks
	surfaceparm nonsolid
}

textures/common/return_ai_trigger
{
	qer_trans 0.32
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}