// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_usa_pent_female_upper_lsleeve1";
	a[1] = "c_usa_pent_female_upper_lsleeve1_2";
	a[2] = "c_usa_pent_female_upper_lsleeve1_3";
	return a;
}
