// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_male_jacket_tshirt_1";
	a[1] = "c_mul_civ_club_male_jacket_tshirt_2";
	a[2] = "c_mul_civ_club_male_jacket_tshirt_3";
	return a;
}
