// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_gen_female_body8_1";
	a[1] = "c_mul_civ_gen_female_body8_2";
	a[2] = "c_mul_civ_gen_female_body8_3";
	a[3] = "c_mul_civ_gen_female_body8_4";
	a[4] = "c_mul_civ_gen_female_body8_5";
	return a;
}
