// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_bra_pants_1";
	a[1] = "c_mul_civ_club_bra_pants_2";
	a[2] = "c_mul_civ_club_bra_pants_3";
	a[3] = "c_mul_civ_club_bra_pants_4";
	a[4] = "c_mul_civ_club_bra_pants_5";
	return a;
}
