// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_female_light8_1";
	a[1] = "c_mul_civ_club_female_light8_2";
	a[2] = "c_mul_civ_club_female_light8_3";
	a[3] = "c_mul_civ_club_female_light8_4";
	a[4] = "c_mul_civ_club_female_light8_5";
	return a;
}
