// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_gen_female_body10_1";
	a[1] = "c_mul_civ_gen_female_body10_2";
	a[2] = "c_mul_civ_gen_female_body10_3";
	a[3] = "c_mul_civ_gen_female_body10_4";
	a[4] = "c_mul_civ_gen_female_body10_5";
	return a;
}
