// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_female_light9_1";
	a[1] = "c_mul_civ_club_female_light9_2";
	a[2] = "c_mul_civ_club_female_light9_3";
	a[3] = "c_mul_civ_club_female_light9_4";
	a[4] = "c_mul_civ_club_female_light9_5";
	return a;
}
