// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_female_light6_1";
	a[1] = "c_mul_civ_club_female_light6_2";
	a[2] = "c_mul_civ_club_female_light6_3";
	a[3] = "c_mul_civ_club_female_light6_4";
	a[4] = "c_mul_civ_club_female_light6_5";
	return a;
}
