// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_female_head1";
	a[1] = "c_mul_civ_club_female_head2";
	a[2] = "c_mul_civ_club_female_head5";
	a[3] = "c_mul_civ_club_female_head4";
	return a;
}
