// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_long_dress4_1";
	a[1] = "c_mul_civ_club_long_dress4_2";
	a[2] = "c_mul_civ_club_long_dress4_3";
	a[3] = "c_mul_civ_club_long_dress4_4";
	a[4] = "c_mul_civ_club_long_dress4_5";
	return a;
}
