// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_usa_pent_female_head1";
	a[1] = "c_usa_pent_female_head2";
	a[2] = "c_usa_pent_female_head3";
	a[3] = "c_usa_pent_female_head4";
	a[4] = "c_usa_pent_female_head5";
	return a;
}
