// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_vtn_civ_macv_ub_short_sleeve_1";
	a[1] = "c_vtn_civ_macv_ub_short_sleeve_2";
	a[2] = "c_vtn_civ_macv_ub_short_sleeve_3";
	a[3] = "c_vtn_civ_macv_ub_long_sleeve_1";
	a[4] = "c_vtn_civ_macv_ub_long_sleeve_2";
	a[5] = "c_vtn_civ_macv_ub_long_sleeve_3";
	return a;
}
