// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "hat_prague_civ_a";
	a[1] = "hat_prague_civ_b";
	a[2] = "hat_prague_civ_c";
	a[3] = "hat_prague_civ_d";
	a[4] = "hat_prague_civ_e";
	a[5] = "hat_prague_civ_f";
	return a;
}
