// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_prague_civ_hero_male_a";
	a[1] = "head_prague_civ_hero_male_b";
	a[2] = "head_prague_civ_hero_male_c";
	a[3] = "head_prague_civ_hero_male_d";
	a[4] = "head_prague_civ_hero_male_e";
	a[5] = "head_prague_civ_hero_male_f";
	return a;
}
