// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_russian_military_assault_a";
	a[1] = "body_russian_military_shotgun_a_airborne";
	a[2] = "body_russian_military_assault_a_airborne";
	return a;
}
