// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_rangers_a";
	a[1] = "head_rangers_b";
	a[2] = "head_tank_a";
	a[3] = "head_tank_b";
	a[4] = "head_tank_bb";
	a[5] = "head_tank_c";
	return a;
}
