// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_henchmen_a";
	a[1] = "head_henchmen_aa";
	a[2] = "head_henchmen_aaa";
	a[3] = "head_henchmen_b";
	a[4] = "head_henchmen_bb";
	a[5] = "head_henchmen_bbb";
	a[6] = "head_henchmen_c";
	a[7] = "head_henchmen_cc";
	return a;
}
