// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_russian_military_aa";
	a[1] = "head_russian_military_c";
	a[2] = "head_russian_military_a";
	a[3] = "head_russian_military_f";
	return a;
}
