// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_ally_gign_paris_leader (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="fullbody_gign_paris_hero"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "allies";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.2;
	self.health = 100;
	self.secondaryweapon = "";
	self.sidearm = "coltanaconda";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	switch( codescripts\character::get_random_weapon(5) )
	{
	case 0:
		self.weapon = "g36c";
		break;
	case 1:
		self.weapon = "g36c_acog";
		break;
	case 2:
		self.weapon = "g36c_grenadier";
		break;
	case 3:
		self.weapon = "g36c_reflex";
		break;
	case 4:
		self.weapon = "g36c_silencer";
		break;
	}

	character\character_gign_paris_hero::main();
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\character_gign_paris_hero::precache();

	precacheItem("g36c");
	precacheItem("g36c_acog");
	precacheItem("g36c_grenadier");
	precacheItem("gl_g36c");
	precacheItem("g36c_reflex");
	precacheItem("g36c_silencer");
	precacheItem("coltanaconda");
	precacheItem("fraggrenade");
}
