// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_ally_juggernaut_dubai (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_complete_sp_juggernaut"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "juggernaut.csv";
	self.team = "allies";
	self.type = "human";
	self.subclass = "juggernaut";
	self.accuracy = 0.2;
	self.health = 3600;
	self.secondaryweapon = "deserteagle";
	self.sidearm = "deserteagle";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 0.000000, 0.000000 );
		self setEngagementMaxDist( 256.000000, 1024.000000 );
	}

	self.weapon = "mk46_grip";

	character\character_sp_juggernaut_dubai::main();
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\character_sp_juggernaut_dubai::precache();

	precacheItem("mk46_grip");
	precacheItem("deserteagle");
	precacheItem("deserteagle");
	precacheItem("fraggrenade");

	//----------------
	maps\_juggernaut::main();
	//----------------
}
