// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_pmc_africa_a";
	a[1] = "head_pmc_africa_b";
	a[2] = "head_pmc_africa_c";
	a[3] = "head_pmc_africa_cc";
	a[4] = "head_pmc_africa_d";
	a[5] = "head_pmc_africa_dd";
	a[6] = "head_pmc_africa_e";
	a[7] = "head_pmc_africa_f";
	a[8] = "head_pmc_africa_ff";
	return a;
}
