// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_honorgd_gear1";
	a[1] = "char_ger_honorgd_gear2";
	a[2] = "char_ger_honorgd_gear3";
	a[3] = "char_ger_honorgd_gear4";
	a[4] = "char_ger_honorgd_gear5";
	a[5] = "char_ger_honorgd_gear5";
	a[6] = "char_ger_honorgd_gear5";
	a[7] = "char_ger_honorgd_gear5";
	a[8] = "char_ger_honorgd_gear5";
	a[9] = "char_ger_honorgd_gear6";
	a[10] = "char_ger_honorgd_gear6";
	a[11] = "char_ger_honorgd_gear6";
	a[12] = "char_ger_honorgd_gear6";
	a[13] = "char_ger_honorgd_gear6";
	a[14] = "char_ger_honorgd_gear7";
	a[15] = "char_ger_honorgd_gear7";
	a[16] = "char_ger_honorgd_gear7";
	a[17] = "char_ger_honorgd_gear7";
	a[18] = "char_ger_honorgd_gear7";
	a[19] = "char_ger_honorgd_gear8";
	a[20] = "char_ger_honorgd_gear8";
	a[21] = "char_ger_honorgd_gear8";
	a[22] = "char_ger_honorgd_gear8";
	a[23] = "char_ger_honorgd_gear8";
	return a;
}
