// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_afg_muhajadeen_head_1_1";
	a[1] = "c_afg_muhajadeen_head_1_2";
	a[2] = "c_afg_muhajadeen_head_1_3";
	a[3] = "c_afg_muhajadeen_head_2_1";
	a[4] = "c_afg_muhajadeen_head_2_2";
	a[5] = "c_afg_muhajadeen_head_2_3";
	a[6] = "c_afg_muhajadeen_head_3_1";
	a[7] = "c_afg_muhajadeen_head_3_2";
	a[8] = "c_afg_muhajadeen_head_3_3";
	return a;
}
