// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_jinan_captain_head1";
	a[1] = "c_mul_jinan_captain_head2";
	a[2] = "c_mul_jinan_captain_head3";
	a[3] = "c_mul_jinan_captain_head4";
	a[4] = "c_mul_jinan_captain_head5";
	a[5] = "c_mul_jinan_captain_head6";
	return a;
}
