// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_female_head1_sil";
	a[1] = "c_mul_civ_club_female_head2_sil";
	a[2] = "c_mul_civ_club_female_head3_sil";
	a[3] = "c_mul_civ_club_female_head4_sil";
	a[4] = "c_mul_civ_club_female_head5_sil";
	return a;
}
