// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_prisoner_headwear4";
	a[1] = "c_rus_prisoner_headwear4";
	a[2] = "c_rus_prisoner_headwear4";
	a[3] = "c_rus_prisoner_headwear4";
	a[4] = "c_rus_prisoner_headwear4";
	a[5] = "c_rus_prisoner_headwear4";
	return a;
}
