// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_yem_houthis_light_body";
	a[1] = "c_yem_houthis_light_body_2";
	a[2] = "c_yem_houthis_light_body_3";
	a[3] = "c_yem_houthis_light_body_4";
	return a;
}
