// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\elite_variants::getnextmodel();
	self setModel( body );
	self attach("lc_thug_4_head", "", false);
	self attach("hands_white_1", "", false);
	hatModel = xmodelalias\eco_soldier_D_beret_alias::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\elite_variants::main());
	precacheModel("lc_thug_4_head");
	precacheModel("hands_white_1");
	codescripts\character::precacheModelArray(xmodelalias\eco_soldier_D_beret_alias::main());
}
