// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\elite_variants::getnextmodel();
	self setModel( body );
	self attach("mi6_agent_2_head", "", false);
	self attach("hands_white_1", "", false);
	hatModel = xmodelalias\sinkhole_mi6b_facial_alias::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\elite_variants::main());
	precacheModel("mi6_agent_2_head");
	precacheModel("hands_white_1");
	codescripts\character::precacheModelArray(xmodelalias\sinkhole_mi6b_facial_alias::main());
}
