// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("haines_tux_body");
	self attach("haines_tux_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("haines_tux_body");
	precacheModel("haines_tux_head");
}
