// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\eco_soldier_bodies::getnextmodel();
	self setModel( body );
	self attach("eco_soldier_C_head", "", false);
	hatModel = xmodelalias\eco_soldier_C_beret_alias::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\eco_soldier_bodies::main());
	precacheModel("eco_soldier_C_head");
	codescripts\character::precacheModelArray(xmodelalias\eco_soldier_C_beret_alias::main());
}
