// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\elite_variants::getnextmodel();
	self setModel( body );
	self attach("elite_head", "", false);
	self attach("hands_black_1", "", false);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\elite_variants::main());
	precacheModel("elite_head");
	precacheModel("hands_black_1");
}
