// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\thug_bodies_barge::getnextmodel();
	self setModel( body );
	self attach("body_guard_2_head_barge", "", false);
	hatModel = xmodelalias\body_guard_2_facial_alias::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\thug_bodies_barge::main());
	precacheModel("body_guard_2_head_barge");
	codescripts\character::precacheModelArray(xmodelalias\body_guard_2_facial_alias::main());
}
