// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("dealer_body");
	self attach("dealer_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("dealer_body");
	precacheModel("dealer_head");
}
