// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("bond_train_body");
	self attach("bond_train_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("bond_train_body");
	precacheModel("bond_train_head");
}
