// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\elite_variants::getnextmodel();
	self setModel( body );
	self attach("sinkhole_thug_head", "", false);
	self attach("hands_black_1", "", false);
	hatModel = xmodelalias\sinkhole_ob_lt_facial_alias::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\elite_variants::main());
	precacheModel("sinkhole_thug_head");
	precacheModel("hands_black_1");
	codescripts\character::precacheModelArray(xmodelalias\sinkhole_ob_lt_facial_alias::main());
}
