// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(10))
	{
	case 0:
		character\mp_american_normandy_braeburn::main();
		break;
	case 1:
		character\mp_american_normandy_david::main();
		break;
	case 2:
		character\mp_american_normandy_frank::main();
		break;
	case 3:
		character\mp_american_normandy_grant::main();
		break;
	case 4:
		character\mp_american_normandy_harry::main();
		break;
	case 5:
		character\mp_american_normandy_medicwells::main();
		break;
	case 6:
		character\mp_american_normandy_mo::main();
		break;
	case 7:
		character\mp_american_normandy_preston::main();
		break;
	case 8:
		character\mp_american_normandy_randall::main();
		break;
	case 9:
		character\mp_american_normandy_wolf::main();
		break;
	}
}

precache()
{
	character\mp_american_normandy_braeburn::precache();
	character\mp_american_normandy_david::precache();
	character\mp_american_normandy_frank::precache();
	character\mp_american_normandy_grant::precache();
	character\mp_american_normandy_harry::precache();
	character\mp_american_normandy_medicwells::precache();
	character\mp_american_normandy_mo::precache();
	character\mp_american_normandy_preston::precache();
	character\mp_american_normandy_randall::precache();
	character\mp_american_normandy_wolf::precache();
}
