// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(6))
	{
	case 0:
		character\mp_british_normandy_boon::main();
		break;
	case 1:
		character\mp_british_normandy_chance::main();
		break;
	case 2:
		character\mp_british_normandy_harry::main();
		break;
	case 3:
		character\mp_british_normandy_joel::main();
		break;
	case 4:
		character\mp_british_normandy_macgregor::main();
		break;
	case 5:
		character\mp_british_normandy_paul::main();
		break;
	}
}

precache()
{
	character\mp_british_normandy_boon::precache();
	character\mp_british_normandy_chance::precache();
	character\mp_british_normandy_harry::precache();
	character\mp_british_normandy_joel::precache();
	character\mp_british_normandy_macgregor::precache();
	character\mp_british_normandy_paul::precache();
}
