// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(2))
	{
	case 0:
		character\mp_german_winterdark::main();
		break;
	case 1:
		character\mp_german_winterdark_masked::main();
		break;
	}
}

precache()
{
	character\mp_german_winterdark::precache();
	character\mp_german_winterdark_masked::precache();
}
