// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch(randomint(4))
	{
	case 0:
		character\mp_russian_coat_jesse::main();
		break;
	case 1:
		character\mp_russian_coat_jon::main();
		break;
	case 2:
		character\mp_russian_coat_popov::main();
		break;
	case 3:
		character\mp_russian_coat_volsky::main();
		break;
	}
}

precache()
{
	character\mp_russian_coat_jesse::precache();
	character\mp_russian_coat_jon::precache();
	character\mp_russian_coat_popov::precache();
	character\mp_russian_coat_volsky::precache();
}
