// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_sniper");
	self attach("head_mp_opforce_david", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_sniper");
	precacheModel("head_mp_opforce_david");
	precacheModel("viewhands_op_force");
}
