// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_arab_regular_sniper");
	self attach("head_mp_arab_regular_sadiq", "", true);
	self.hatModel = "head_mp_arab_regular_sadiq_beret";
	self attach(self.hatModel);
	self setViewmodel("viewhands_op_force");
	self.voice = "arab";
}

precache()
{
	precacheModel("body_mp_arab_regular_sniper");
	precacheModel("head_mp_arab_regular_sadiq");
	precacheModel("head_mp_arab_regular_sadiq_beret");
	precacheModel("viewhands_op_force");
}
