// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_opforce_eningeer");
	self attach("head_mp_opforce_ski_mask", "", true);
	self setViewmodel("viewhands_op_force");
	self.voice = "russian";
}

precache()
{
	precacheModel("body_mp_opforce_eningeer");
	precacheModel("head_mp_opforce_ski_mask");
	precacheModel("viewhands_op_force");
}
