// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_mp_usmc_woodland_specops");
	self attach("head_mp_usmc_tactical_mich_stripes_nomex", "", true);
	self setViewmodel("viewmodel_base_viewhands");
	self.voice = "british";
}

precache()
{
	precacheModel("body_mp_usmc_woodland_specops");
	precacheModel("head_mp_usmc_tactical_mich_stripes_nomex");
	precacheModel("viewmodel_base_viewhands");
}
