// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("bond_whites_body");
	self attach("bond_whites_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("bond_whites_body");
	precacheModel("bond_whites_head");
}
