// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("bond_rain_body");
	self attach("bond_rain_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("bond_rain_body");
	precacheModel("bond_rain_head");
}
