// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: class_sniper
// Convert Time: 07/19/2012 22:02:38
#include common_scripts\utility;

precache()
{
	PrecacheModel( "c_mul_mp_pmc_sniper_fb" );
	PrecacheModel( "c_mul_mp_pmc_longsleeve_viewhands" );

	if ( level.multiTeam )	
	{
		game["set_player_model"]["team4"]["rifle"] = ::set_player_model;
	}
	else
	{
		game["set_player_model"]["axis"]["rifle"] = ::set_player_model;
	}
}

set_player_model()
{
	self SetModel( "c_mul_mp_pmc_sniper_fb" );
	self SetViewModel( "c_mul_mp_pmc_longsleeve_viewhands" );

	heads = [];
}

