// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_chemwar_russian_assault_d");
	codescripts\character::attachHead( "alias_chemwar_russian_heads_masked", xmodelalias\alias_chemwar_russian_heads_masked::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_chemwar_russian_assault_d");
	codescripts\character::precacheModelArray(xmodelalias\alias_chemwar_russian_heads_masked::main());
}
