// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_gign_paris_smg");
	codescripts\character::attachHead( "alias_gign_heads", xmodelalias\alias_gign_heads::main() );
	self.voice = "french";
}

precache()
{
	precacheModel("body_gign_paris_smg");
	codescripts\character::precacheModelArray(xmodelalias\alias_gign_heads::main());
}
