// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_assault_ba");
	codescripts\character::attachHead( "alias_delta_elite_heads", xmodelalias\alias_delta_elite_heads::main() );
	self.voice = "delta";
}

precache()
{
	precacheModel("body_delta_elite_assault_ba");
	codescripts\character::precacheModelArray(xmodelalias\alias_delta_elite_heads::main());
}
