// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_assault_a_black");
	codescripts\character::attachHead( "alias_so_veteran_ar_heads", xmodelalias\alias_so_veteran_ar_heads::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russian_military_assault_a_black");
	codescripts\character::precacheModelArray(xmodelalias\alias_so_veteran_ar_heads::main());
}
