// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_assault_a");
	self attach("head_russian_military_aa", "", true);
	self.headModel = "head_russian_military_aa";
	self setViewmodel("viewhands_russian_a");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_assault_a");
	precacheModel("head_russian_military_aa");
	precacheModel("viewhands_russian_a");
}
