// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_smg_a_woodland");
	self attach("head_russian_military_e", "", true);
	self.headModel = "head_russian_military_e";
	self setViewmodel("viewhands_russian_c");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_smg_a_woodland");
	precacheModel("head_russian_military_e");
	precacheModel("viewhands_russian_c");
}
