// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_lmg_a_arctic");
	codescripts\character::attachHead( "alias_russian_military_arctic_heads", xmodelalias\alias_russian_military_arctic_heads::main() );
	self setViewmodel("viewhands_russian_d");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_lmg_a_arctic");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_arctic_heads::main());
	precacheModel("viewhands_russian_d");
}
