// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_delta_elite_smg_b");
	codescripts\character::attachHead( "alias_delta_elite_heads_longsleeves", xmodelalias\alias_delta_elite_heads_longsleeves::main() );
	self setViewmodel("viewhands_delta");
	self.voice = "delta";
}

precache()
{
	precacheModel("mp_body_delta_elite_smg_b");
	codescripts\character::precacheModelArray(xmodelalias\alias_delta_elite_heads_longsleeves::main());
	precacheModel("viewhands_delta");
}
