// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_rus_guard_helm1";
	a[1] = "char_rus_guard_hat";
	a[2] = "char_rus_guard_ushankadown1";
	a[3] = "char_rus_guard_ushankaup1";
	return a;
}
