// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_rus_guard_head1_1";
	a[1] = "char_rus_guard_head1_2";
	a[2] = "char_rus_guard_head1_3";
	a[3] = "char_rus_guard_head1_4";
	a[4] = "char_rus_guard_head2_1";
	a[5] = "char_rus_guard_head2_2";
	a[6] = "char_rus_guard_head2_3";
	a[7] = "char_rus_guard_head2_4";
	a[8] = "char_rus_guard_head3_1";
	a[9] = "char_rus_guard_head3_2";
	a[10] = "char_rus_guard_head3_3";
	a[11] = "char_rus_guard_head3_4";
	a[12] = "char_rus_guard_head4_1";
	a[13] = "char_rus_guard_head4_2";
	a[14] = "char_rus_guard_head4_3";
	a[15] = "char_rus_guard_head4_4";
	return a;
}
