// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_usa_navy_wetsailor_cap3";
	a[1] = "char_usa_navy_wetsailor_nocap";
	a[2] = "char_usa_navy_wetsailor_nocap";
	a[3] = "char_usa_navy_wetsailor_nocap";
	return a;
}
