// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_ger_waffen_head1_1";
	a[1] = "char_ger_waffen_head1_2";
	a[2] = "char_ger_waffen_head1_3";
	a[3] = "char_ger_waffen_head1_4";
	a[4] = "char_ger_waffen_head1_5";
	a[5] = "char_ger_waffen_head1_6";
	a[6] = "char_ger_waffen_head2_1";
	a[7] = "char_ger_waffen_head2_2";
	a[8] = "char_ger_waffen_head2_3";
	a[9] = "char_ger_waffen_head2_4";
	a[10] = "char_ger_waffen_head2_5";
	a[11] = "char_ger_waffen_head2_6";
	a[12] = "char_ger_waffen_head3_1";
	a[13] = "char_ger_waffen_head3_2";
	a[14] = "char_ger_waffen_head3_3";
	a[15] = "char_ger_waffen_head3_4";
	a[16] = "char_ger_waffen_head3_5";
	a[17] = "char_ger_waffen_head3_6";
	a[18] = "char_ger_waffen_head4_1";
	a[19] = "char_ger_waffen_head4_2";
	a[20] = "char_ger_waffen_head4_3";
	a[21] = "char_ger_waffen_head4_4";
	a[22] = "char_ger_waffen_head4_5";
	a[23] = "char_ger_waffen_head4_6";
	return a;
}
