#include maps\_anim;
main()
{
	// Autogenerated by AnimSounds. Threaded off so that it can be placed before _load( has to create level.scr_notetrack first ).
	thread init_animsounds();
}

init_animsounds()
{
	waittillframeend;
	addNotetrack_animSound( "playerview", "intro", "hit", "melee_hit" );
	addNotetrack_animSound( "playerview", "car_exit", "kick", "curb_stomp" ); 
	addNotetrack_animSound( "ending_alasad", "ending_execution", "cock_gun", "assassination_hammer" ); 
	addNotetrack_animSound( "ending_alasad", "ending_execution", "fire_gun", "assassination_shot" ); 
}
