// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "cas_thug_3_goatee";
	a[1] = "thug_bald";
	a[2] = "cas_thug_3_stache";
	a[3] = "thug_bald";
	a[4] = "cas_thug_3_chin";
	a[5] = "cas_thug_3_beard";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["cas_thug_3_beards_Body"] ) )
	{
		startIndex = randomint(6);
		level.nextXModel["cas_thug_3_beards_Body"] = startIndex;
	}
	index = level.nextXModel["cas_thug_3_beards_Body"];
	level.nextXModel["cas_thug_3_beards_Body"] = index+1;

	if( level.nextXModel["cas_thug_3_beards_Body"] >= 6 )
		level.nextXModel["cas_thug_3_beards_Body"] = 0;

	if( (index >= 6) || (index < 0))
		index = randomint(6);

	a = main();
	return a[ index ];
}
