// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "thug_bald";
	a[1] = "casino_male_1_facial_beard";
	a[2] = "casino_male_1_facial_goatee";
	a[3] = "casino_male_1_facial_stache";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["casino_male_1_facial_Body"] ) )
	{
		startIndex = randomint(4);
		level.nextXModel["casino_male_1_facial_Body"] = startIndex;
	}
	index = level.nextXModel["casino_male_1_facial_Body"];
	level.nextXModel["casino_male_1_facial_Body"] = index+1;

	if( level.nextXModel["casino_male_1_facial_Body"] >= 4 )
		level.nextXModel["casino_male_1_facial_Body"] = 0;

	if( (index >= 4) || (index < 0))
		index = randomint(4);

	a = main();
	return a[ index ];
}
