// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "lc_thug_4_beard_stache";
	a[1] = "eco_soldier_C_beret";
	a[2] = "mp_mi6_helmet_1";
	a[3] = "lc_thug_4_beard_goatee";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["eco_soldier_D_beret_alias_Body"] ) )
	{
		startIndex = randomint(4);
		level.nextXModel["eco_soldier_D_beret_alias_Body"] = startIndex;
	}
	index = level.nextXModel["eco_soldier_D_beret_alias_Body"];
	level.nextXModel["eco_soldier_D_beret_alias_Body"] = index+1;

	if( level.nextXModel["eco_soldier_D_beret_alias_Body"] >= 4 )
		level.nextXModel["eco_soldier_D_beret_alias_Body"] = 0;

	if( (index >= 4) || (index < 0))
		index = randomint(4);

	a = main();
	return a[ index ];
}
