// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_guard_3_facial_glasses";
	a[1] = "thug_bald";
	a[2] = "body_guard_3_facial_stache";
	a[3] = "sinkhole_thug_helmet_bg3";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["sinkhole_bg3_facial_alias_Body"] ) )
	{
		startIndex = randomint(4);
		level.nextXModel["sinkhole_bg3_facial_alias_Body"] = startIndex;
	}
	index = level.nextXModel["sinkhole_bg3_facial_alias_Body"];
	level.nextXModel["sinkhole_bg3_facial_alias_Body"] = index+1;

	if( level.nextXModel["sinkhole_bg3_facial_alias_Body"] >= 4 )
		level.nextXModel["sinkhole_bg3_facial_alias_Body"] = 0;

	if( (index >= 4) || (index < 0))
		index = randomint(4);

	a = main();
	return a[ index ];
}
