// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "sinkhole_thug_helmet_ob_lt";
	a[1] = "thug_bald";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["sinkhole_ob_lt_facial_alias_Body"] ) )
	{
		startIndex = randomint(2);
		level.nextXModel["sinkhole_ob_lt_facial_alias_Body"] = startIndex;
	}
	index = level.nextXModel["sinkhole_ob_lt_facial_alias_Body"];
	level.nextXModel["sinkhole_ob_lt_facial_alias_Body"] = index+1;

	if( level.nextXModel["sinkhole_ob_lt_facial_alias_Body"] >= 2 )
		level.nextXModel["sinkhole_ob_lt_facial_alias_Body"] = 0;

	if( (index >= 2) || (index < 0))
		index = randomint(2);

	a = main();
	return a[ index ];
}
