// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "lc_thug_1_body_barge";
	a[1] = "body_guard_2_body_purpletie_barge";
	a[2] = "body_guard_2_body_barge";
	a[3] = "body_guard_3_body_blue_barge";
	a[4] = "body_guard_1_body_barge";
	a[5] = "body_guard_2_body_tantie_barge";
	a[6] = "lc_thug_1_body_bluesweater_barge";
	a[7] = "body_guard_3_body_barge";
	a[8] = "body_guard_1_body_tan_barge";
	a[9] = "body_guard_2_body_redtie_barge";
	a[10] = "body_guard_1_body_blue_barge";
	a[11] = "body_guard_2_body_blacktie_barge";
	a[12] = "lc_thug_1_body_brownsweater_barge";
	a[13] = "body_guard_3_body_tan_barge";
	a[14] = "body_guard_1_body_olive_barge";
	a[15] = "body_guard_2_body_greentie_barge";
	a[16] = "body_guard_3_body_black_barge";
	a[17] = "body_guard_2_body_blacktie_barge";
	a[18] = "lc_thug_1_body_greysweater_barge";
	a[19] = "body_guard_3_body_olive_barge";
	a[20] = "body_guard_1_body_yellow_barge";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["thug_bodies_barge_Body"] ) )
	{
		startIndex = randomint(21);
		level.nextXModel["thug_bodies_barge_Body"] = startIndex;
	}
	index = level.nextXModel["thug_bodies_barge_Body"];
	level.nextXModel["thug_bodies_barge_Body"] = index+1;

	if( level.nextXModel["thug_bodies_barge_Body"] >= 21 )
		level.nextXModel["thug_bodies_barge_Body"] = 0;

	if( (index >= 21) || (index < 0))
		index = randomint(21);

	a = main();
	return a[ index ];
}
