// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "tourist_1_facial_goatee_glasses_3";
	a[1] = "tourist_1_facial_beard";
	a[2] = "thug_bald";
	a[3] = "tourist_1_facial_stache";
	a[4] = "tourist_1_facial_beard_glasses_3";
	a[5] = "tourist_1_facial_goatee";
	a[6] = "tourist_1_facial_stache_glasses_6";
	a[7] = "tourist_1_facial_beard_glasses_6";
	a[8] = "tourist_1_facial_stache_glasses_3";
	a[9] = "tourist_1_facial_goatee_glasses_6";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["tourist_1_facials_Body"] ) )
	{
		startIndex = randomint(10);
		level.nextXModel["tourist_1_facials_Body"] = startIndex;
	}
	index = level.nextXModel["tourist_1_facials_Body"];
	level.nextXModel["tourist_1_facials_Body"] = index+1;

	if( level.nextXModel["tourist_1_facials_Body"] >= 10 )
		level.nextXModel["tourist_1_facials_Body"] = 0;

	if( (index >= 10) || (index < 0))
		index = randomint(10);

	a = main();
	return a[ index ];
}
