// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_So_Enemy_Bigdog (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER MAKEROOM UNDELETABLE ENEMYINFO SCRIPT_FORCESPAWN SM_PRIORITY
defaultmdl="veh_t6_drone_big_dog"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
MAKEROOM -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for MAKEROOM guys
ENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
SCRIPT_FORCESPAWN -- this AI will spawned even if players can see him spawning.
SM_PRIORITY -- Make the Spawn Manager spawn from this spawner before other spawners.
*/
main()
{
	self.accuracy = 1;
	self.animStateDef = "";
	self.animTree = "\\bigdog.atr";
	self.csvInclude = "char_bigdog.csv";
	self.demoLockOnHighlightDistance = 100;
	self.demoLockOnViewHeightOffset1 = 8;
	self.demoLockOnViewHeightOffset2 = 8;
	self.demoLockOnViewPitchMax1 = 60;
	self.demoLockOnViewPitchMax2 = 60;
	self.demoLockOnViewPitchMin1 = 0;
	self.demoLockOnViewPitchMin2 = 0;
	self.footstepFXTable = "";
	self.footstepPrepend = "";
	self.footstepScriptCallback = 1;
	self.grenadeAmmo = 0;
	self.grenadeWeapon = "claw_grenade_sp";
	self.health = 1000;
	self.precacheScript = "aitype_bigdog.gsc";
	self.secondaryweapon = "";
	self.sidearm = "";
	self.subclass = "regular";
	self.team = "axis";
	self.type = "bigdog";
	self.weapon = "";

	self setEngagementMinDist( 500.000000, 300.000000 );
	self setEngagementMaxDist( 800.000000, 1200.000000 );

	character\c_t6_claw_mk2::main();
	self SetCharacterIndex(0);
}

spawner()
{
	self setspawnerteam("axis");
}

precache(ai_index)
{
	character\c_t6_claw_mk2::precache();

	precacheItem("claw_grenade_sp");

	animscripts\aitype\aitype_bigdog::precache();
}
