// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_zm_zombie_transit_screecher (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER MAKEROOM UNDELETABLE ENEMYINFO SCRIPT_FORCESPAWN SM_PRIORITY
defaultmdl="c_zom_screecher_fb"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
MAKEROOM -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for MAKEROOM guys
ENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
SCRIPT_FORCESPAWN -- this AI will spawned even if players can see him spawning.
SM_PRIORITY -- Make the Spawn Manager spawn from this spawner before other spawners.
*/
#using_animtree("zm_transit_screecher");
reference_anims_from_animtree()
{
	dummy_anim_ref = %ai_zombie_screecher_climb_down_pothole;
	dummy_anim_ref = %ai_zombie_screecher_climb_up_pothole;
	dummy_anim_ref = %ai_zombie_screecher_cower_v1;
	dummy_anim_ref = %ai_zombie_screecher_death_v1;
	dummy_anim_ref = %ai_zombie_screecher_headpull;
	dummy_anim_ref = %ai_zombie_screecher_headpull_fail;
	dummy_anim_ref = %ai_zombie_screecher_headpull_success;
	dummy_anim_ref = %ai_zombie_screecher_jump_land_fail;
	dummy_anim_ref = %ai_zombie_screecher_jump_land_success_fromback;
	dummy_anim_ref = %ai_zombie_screecher_jump_land_success_fromfront;
	dummy_anim_ref = %ai_zombie_screecher_jump_loop;
	dummy_anim_ref = %ai_zombie_screecher_jump_up;
	dummy_anim_ref = %ai_zombie_screecher_run;
	dummy_anim_ref = %ai_zombie_screecher_run_hop;
	dummy_anim_ref = %ai_zombie_screecher_tunnel_traversal;
	dummy_anim_ref = %ai_zombie_screecher_traverse_ground_v1;
}

main()
{
	self.accuracy = 1;
	self.animStateDef = "zm_transit_screecher.asd";
	self.animTree = "zm_transit_screecher.atr";
	self.csvInclude = "";
	self.demoLockOnHighlightDistance = 100;
	self.demoLockOnViewHeightOffset1 = 18;
	self.demoLockOnViewHeightOffset2 = 8;
	self.demoLockOnViewPitchMax1 = 60;
	self.demoLockOnViewPitchMax2 = 60;
	self.demoLockOnViewPitchMin1 = 0;
	self.demoLockOnViewPitchMin2 = 0;
	self.footstepFXTable = "";
	self.footstepPrepend = "";
	self.footstepScriptCallback = 0;
	self.grenadeAmmo = 0;
	self.grenadeWeapon = "";
	self.health = 200;
	self.precacheScript = "";
	self.secondaryweapon = "";
	self.sidearm = "";
	self.subclass = "regular";
	self.team = "axis";
	self.type = "zombie";
	self.weapon = "";

	self setEngagementMinDist( 0.000000, 0.000000 );
	self setEngagementMaxDist( 100.000000, 300.000000 );

	character\c_zom_screecher::main();
	self SetCharacterIndex(0);
}

spawner()
{
	self setspawnerteam("axis");
}

precache(ai_index)
{
	level thread reference_anims_from_animtree();
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_screecher" );

	character\c_zom_screecher::precache();

}
