// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_zm_zombie_transit_avogadro (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER MAKEROOM UNDELETABLE ENEMYINFO SCRIPT_FORCESPAWN SM_PRIORITY
defaultmdl="c_zom_electrician_fb"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
MAKEROOM -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for MAKEROOM guys
ENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
SCRIPT_FORCESPAWN -- this AI will spawned even if players can see him spawning.
SM_PRIORITY -- Make the Spawn Manager spawn from this spawner before other spawners.
*/
#using_animtree("zm_transit_avogadro");
reference_anims_from_animtree()
{
	dummy_anim_ref = %ai_zombie_avogadro_arrival;
	dummy_anim_ref = %ai_zombie_avogadro_exit;
	dummy_anim_ref = %ai_zombie_avogadro_bus_attack_back;
	dummy_anim_ref = %ai_zombie_avogadro_bus_attack_front;
	dummy_anim_ref = %ai_zombie_avogadro_bus_attack_left;
	dummy_anim_ref = %ai_zombie_avogadro_bus_attack_right;
	dummy_anim_ref = %ai_zombie_avogadro_bus_attack_knocked_off;
	dummy_anim_ref = %ai_zombie_avogadro_bus_pain_long;
	dummy_anim_ref = %ai_zombie_avogadro_bus_pain_med;
	dummy_anim_ref = %ai_zombie_avogadro_bus_pain_short;
	dummy_anim_ref = %ai_zombie_avogadro_idle_v1;
	dummy_anim_ref = %ai_zombie_avogadro_melee_attack_v1;
	dummy_anim_ref = %ai_zombie_avogadro_pain_long;
	dummy_anim_ref = %ai_zombie_avogadro_pain_med;
	dummy_anim_ref = %ai_zombie_avogadro_pain_short;
	dummy_anim_ref = %ai_zombie_avogadro_ranged_attack_v1;
	dummy_anim_ref = %ai_zombie_avogadro_ranged_attack_v1_loop;
	dummy_anim_ref = %ai_zombie_avogadro_ranged_attack_v1_end;
	dummy_anim_ref = %ai_zombie_avogadro_run_v1;
	dummy_anim_ref = %ai_zombie_avogadro_run_v1_twitch;
	dummy_anim_ref = %ai_zombie_avogadro_sprint_v1;
	dummy_anim_ref = %ai_zombie_avogadro_sprint_v1_twitch;
	dummy_anim_ref = %ai_zombie_avogadro_walk_v1;
	dummy_anim_ref = %ai_zombie_avogadro_walk_v1_twitch;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_forward_long;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_forward_med;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_forward_short;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_left_long;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_left_med;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_left_short;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_right_long;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_right_med;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_right_short;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_back_long;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_back_med;
	dummy_anim_ref = %ai_zombie_avogadro_teleport_back_short;
	dummy_anim_ref = %ai_zombie_climb_down_pothole;
	dummy_anim_ref = %ai_zombie_crawl_climb_down_pothole;
	dummy_anim_ref = %ai_zombie_climb_up_pothole;
	dummy_anim_ref = %ai_zombie_crawl_climb_up_pothole;
	dummy_anim_ref = %ai_zombie_jump_down_48;
	dummy_anim_ref = %ai_zombie_crawl_jump_down_48;
	dummy_anim_ref = %ai_zombie_jump_down_96;
	dummy_anim_ref = %ai_zombie_crawl_jump_down_96;
	dummy_anim_ref = %ai_zombie_jump_down_127;
	dummy_anim_ref = %ai_zombie_crawl_jump_down_127;
	dummy_anim_ref = %ai_zombie_jump_down_190;
	dummy_anim_ref = %ai_zombie_crawl_jump_down_189;
	dummy_anim_ref = %ai_zombie_jump_down_222;
	dummy_anim_ref = %ai_zombie_crawl_jump_down_222;
	dummy_anim_ref = %ai_zombie_jump_up_127;
	dummy_anim_ref = %ai_zombie_crawl_jump_up_127;
	dummy_anim_ref = %ai_zombie_traverse_v1;
	dummy_anim_ref = %ai_zombie_traverse_v2;
	dummy_anim_ref = %ai_zombie_traverse_v5;
	dummy_anim_ref = %ai_zombie_traverse_v6;
	dummy_anim_ref = %ai_zombie_traverse_v7;
	dummy_anim_ref = %ai_zombie_traverse_crawl_v1;
	dummy_anim_ref = %ai_zombie_traverse_v4;
}

main()
{
	self.accuracy = 1;
	self.animStateDef = "zm_transit_avogadro.asd";
	self.animTree = "zm_transit_avogadro.atr";
	self.csvInclude = "";
	self.demoLockOnHighlightDistance = 100;
	self.demoLockOnViewHeightOffset1 = 70;
	self.demoLockOnViewHeightOffset2 = 8;
	self.demoLockOnViewPitchMax1 = 60;
	self.demoLockOnViewPitchMax2 = 60;
	self.demoLockOnViewPitchMin1 = -15;
	self.demoLockOnViewPitchMin2 = 0;
	self.footstepFXTable = "";
	self.footstepPrepend = "";
	self.footstepScriptCallback = 0;
	self.grenadeAmmo = 0;
	self.grenadeWeapon = "";
	self.health = 200;
	self.precacheScript = "";
	self.secondaryweapon = "";
	self.sidearm = "";
	self.subclass = "regular";
	self.team = "axis";
	self.type = "zombie";
	self.weapon = "";

	self setEngagementMinDist( 0.000000, 0.000000 );
	self setEngagementMaxDist( 100.000000, 300.000000 );

	character\c_zom_electrician::main();
	self SetCharacterIndex(0);
}

spawner()
{
	self setspawnerteam("axis");
}

precache(ai_index)
{
	level thread reference_anims_from_animtree();
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_avogadro" );

	character\c_zom_electrician::precache();

}
