// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_prague_civilian_nonhood_bodies::main());
	self attach("head_prague_civ_male_a_hat", "", true);
	self.headModel = "head_prague_civ_male_a_hat";
	if ( isendstr( self.headModel, "_hat" ) )
		codescripts\character::attachHat( "alias_prague_civilian_nonhood_hats", xmodelalias\alias_prague_civilian_nonhood_hats::main() );
	self.voice = "czech";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_prague_civilian_nonhood_bodies::main());
	precacheModel("head_prague_civ_male_a_hat");
	codescripts\character::precacheModelArray(xmodelalias\alias_prague_civilian_nonhood_hats::main());
}
