// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_price_europe_assault_cc");
	self attach("head_price_europe_a_boonie", "", true);
	self.headModel = "head_price_europe_a_boonie";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_price_europe_assault_cc");
	precacheModel("head_price_europe_a_boonie");
}
