// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_russian_military_gasmask_bodies::main());
	self attach("head_russian_military_f", "", true);
	self.headModel = "head_russian_military_f";
	self.voice = "russian";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_gasmask_bodies::main());
	precacheModel("head_russian_military_f");
}
