// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_sandman_seal_udt");
	codescripts\character::attachHead( "alias_seal_udt_heads_dive", xmodelalias\alias_seal_udt_heads_dive::main() );
	self.voice = "delta";
}

precache()
{
	precacheModel("body_hero_sandman_seal_udt");
	codescripts\character::precacheModelArray(xmodelalias\alias_seal_udt_heads_dive::main());
}
