// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_fso_vest_e");
	self attach("head_fso_commander_hat", "", true);
	self.headModel = "head_fso_commander_hat";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_fso_vest_e");
	precacheModel("head_fso_commander_hat");
}
