// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_kamarov_lmg_a");
	self attach("head_hero_kamarov_a", "", true);
	self.headModel = "head_hero_kamarov_a";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_hero_kamarov_lmg_a");
	precacheModel("head_hero_kamarov_a");
}
