// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_dubai_male_b_alt");
	self attach("head_dubai_male_a", "", true);
	self.headModel = "head_dubai_male_a";
	self.voice = "arab";
}

precache()
{
	precacheModel("body_dubai_male_b_alt");
	precacheModel("head_dubai_male_a");
}
