// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_dubai_male_b");
	self attach("head_dubai_male_d", "", true);
	self.headModel = "head_dubai_male_d";
	self.voice = "arab";
}

precache()
{
	precacheModel("body_dubai_male_b");
	precacheModel("head_dubai_male_d");
}
