// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_smg_a_airborne");
	codescripts\character::attachHead( "alias_so_regular_smg_heads", xmodelalias\alias_so_regular_smg_heads::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russian_military_smg_a_airborne");
	codescripts\character::precacheModelArray(xmodelalias\alias_so_regular_smg_heads::main());
}
