// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_sandman_delta");
	self attach("head_hero_sandman_gasmask", "", true);
	self.headModel = "head_hero_sandman_gasmask";
	self.voice = "delta";
}

precache()
{
	precacheModel("body_hero_sandman_delta");
	precacheModel("head_hero_sandman_gasmask");
}
