// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_rpg_a_airborne");
	self attach("head_russian_military_c", "", true);
	self.headModel = "head_russian_military_c";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russian_military_rpg_a_airborne");
	precacheModel("head_russian_military_c");
}
