// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russianwoodland_assault_a_dusty");
	self attach("head_russianwoodland_a_dusty", "", true);
	self.headModel = "head_russianwoodland_a_dusty";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russianwoodland_assault_a_dusty");
	precacheModel("head_russianwoodland_a_dusty");
}
