// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\alias_prague_civilian_nonhood_bodies::main());
	codescripts\character::attachHead( "alias_prague_civilian_hero_heads_male", xmodelalias\alias_prague_civilian_hero_heads_male::main() );
	self.voice = "czech";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\alias_prague_civilian_nonhood_bodies::main());
	codescripts\character::precacheModelArray(xmodelalias\alias_prague_civilian_hero_heads_male::main());
}
