// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_president");
	self attach("head_russian_president", "", true);
	self.headModel = "head_russian_president";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russian_president");
	precacheModel("head_russian_president");
}
