// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_prague_civ_male_dd");
	self attach("head_prague_civ_male_b_hat", "", true);
	self.headModel = "head_prague_civ_male_b_hat";
	self.voice = "czech";
}

precache()
{
	precacheModel("body_prague_civ_male_dd");
	precacheModel("head_prague_civ_male_b_hat");
}
