// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_so_juggernaut_blue");
	self attach("head_so_juggernaut_blue_hat", "", true);
	self.headModel = "head_so_juggernaut_blue_hat";
	if ( isendstr( self.headModel, "_hat" ) )
	{
		self.hatModel = "hat_so_juggernaut_blue";
		self attach(self.hatModel);
	}
	self.voice = "russian";
}

precache()
{
	precacheModel("body_so_juggernaut_blue");
	precacheModel("head_so_juggernaut_blue_hat");
	precacheModel("hat_so_juggernaut_blue");
}
