// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russianwoodland_smg_a");
	self attach("head_russianwoodland_b", "", true);
	self.headModel = "head_russianwoodland_b";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russianwoodland_smg_a");
	precacheModel("head_russianwoodland_b");
}
