// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_fso_suit_a");
	self attach("head_fso_f", "", true);
	self.headModel = "head_fso_f";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_fso_suit_a");
	precacheModel("head_fso_f");
}
