// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("russian_presidents_daughter_body");
	self attach("russian_presidents_daughter_head", "", true);
	self.headModel = "russian_presidents_daughter_head";
	self.voice = "russian";
}

precache()
{
	precacheModel("russian_presidents_daughter_body");
	precacheModel("russian_presidents_daughter_head");
}
