// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_fso_suit_advisor");
	self attach("head_fso_advisor", "", true);
	self.headModel = "head_fso_advisor";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_fso_suit_advisor");
	precacheModel("head_fso_advisor");
}
