// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_chemwar_russian_assault_a");
	self.voice = "russian";
}

precache()
{
	precacheModel("fullbody_chemwar_russian_assault_a");
}
