// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_urban_assault_aa");
	codescripts\character::attachHead( "alias_delta_heads", xmodelalias\alias_delta_heads::main() );
	self.voice = "delta";
}

precache()
{
	precacheModel("body_delta_urban_assault_aa");
	codescripts\character::precacheModelArray(xmodelalias\alias_delta_heads::main());
}
