// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_volk_a");
	self attach("head_volk_a", "", true);
	self.headModel = "head_volk_a";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_volk_a");
	precacheModel("head_volk_a");
}
