// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_assault_bb");
	self attach("head_hero_grinch_delta", "", true);
	self.headModel = "head_hero_grinch_delta";
	self.voice = "delta";
}

precache()
{
	precacheModel("body_delta_elite_assault_bb");
	precacheModel("head_hero_grinch_delta");
}
