// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_gign_paris_lmg");
	self attach("head_gign_generic_gasmask", "", true);
	self.headModel = "head_gign_generic_gasmask";
	self.voice = "french";
}

precache()
{
	precacheModel("body_gign_paris_lmg");
	precacheModel("head_gign_generic_gasmask");
}
