// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_india_male_a_alt");
	self attach("head_india_male_c", "", true);
	self.headModel = "head_india_male_c";
	self.voice = "arab";
}

precache()
{
	precacheModel("body_india_male_a_alt");
	precacheModel("head_india_male_c");
}
