// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_africa_civ_male_c");
	codescripts\character::attachHead( "alias_africa_civilian_male_heads", xmodelalias\alias_africa_civilian_male_heads::main() );
	self.voice = "african";
}

precache()
{
	precacheModel("body_africa_civ_male_c");
	codescripts\character::precacheModelArray(xmodelalias\alias_africa_civilian_male_heads::main());
}
