// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_india_female_a");
	self attach("head_india_female_a", "", true);
	self.headModel = "head_india_female_a";
	self.voice = "arab";
}

precache()
{
	precacheModel("body_india_female_a");
	precacheModel("head_india_female_a");
}
