// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_villain_makarov_prague_escape");
	self.voice = "seal";
}

precache()
{
	precacheModel("body_villain_makarov_prague_escape");
}
