// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_russian_military_rpg_a_airborne");
	codescripts\character::attachHead( "alias_russian_military_germany_heads", xmodelalias\alias_russian_military_germany_heads::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_russian_military_rpg_a_airborne");
	codescripts\character::precacheModelArray(xmodelalias\alias_russian_military_germany_heads::main());
}
