// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("fullbody_nikolai_africa_assault_a");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("fullbody_nikolai_africa_assault_a");
}
