// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_india_male_b_alt");
	self attach("head_india_male_d", "", true);
	self.headModel = "head_india_male_d";
	self.voice = "arab";
}

precache()
{
	precacheModel("body_india_male_b_alt");
	precacheModel("head_india_male_d");
}
