// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_chemwar_russian_assault_dd");
	codescripts\character::attachHead( "alias_chemwar_russian_heads", xmodelalias\alias_chemwar_russian_heads::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_chemwar_russian_assault_dd");
	codescripts\character::precacheModelArray(xmodelalias\alias_chemwar_russian_heads::main());
}
