// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_delta_elite_assault_aa");
	codescripts\character::attachHead( "alias_air_crew_heads", xmodelalias\alias_air_crew_heads::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("body_delta_elite_assault_aa");
	codescripts\character::precacheModelArray(xmodelalias\alias_air_crew_heads::main());
}
