// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_shotgun_a");
	self attach("head_russian_military_dd", "", true);
	self.headModel = "head_russian_military_dd";
	self setViewmodel("viewhands_russian_a");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_shotgun_a");
	precacheModel("head_russian_military_dd");
	precacheModel("viewhands_russian_a");
}
