// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_shotgun_a_woodland");
	self attach("head_russian_military_cc", "", true);
	self.headModel = "head_russian_military_cc";
	self setViewmodel("viewhands_russian_c");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_shotgun_a_woodland");
	precacheModel("head_russian_military_cc");
	precacheModel("viewhands_russian_c");
}
