// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_russian_military_smg_a_airborne");
	self attach("head_russian_military_f", "", true);
	self.headModel = "head_russian_military_f";
	self setViewmodel("viewhands_russian_b");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_russian_military_smg_a_airborne");
	precacheModel("head_russian_military_f");
	precacheModel("viewhands_russian_b");
}
