// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_guard_2_facial_beard";
	a[1] = "body_guard_2_facial_chin";
	a[2] = "body_guard_2_facial_stache";
	a[3] = "body_guard_2_facial_goatee";
	a[4] = "thug_bald";
	a[5] = "body_guard_2_facial_glasses";
	a[6] = "body_guard_2_facial_goatee_glasses";
	a[7] = "body_guard_2_facial_goatee_brown";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["body_guard_2_facial_alias_Body"] ) )
	{
		startIndex = randomint(8);
		level.nextXModel["body_guard_2_facial_alias_Body"] = startIndex;
	}
	index = level.nextXModel["body_guard_2_facial_alias_Body"];
	level.nextXModel["body_guard_2_facial_alias_Body"] = index+1;

	if( level.nextXModel["body_guard_2_facial_alias_Body"] >= 8 )
		level.nextXModel["body_guard_2_facial_alias_Body"] = 0;

	if( (index >= 8) || (index < 0))
		index = randomint(8);

	a = main();
	return a[ index ];
}
