// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "thug_bald";
	a[1] = "cas_thug_2_stache";
	a[2] = "cas_thug_2_chin";
	a[3] = "cas_thug_2_goatee";
	a[4] = "thug_bald";
	a[5] = "cas_thug_2_beard";
	a[6] = "thug_bald";
	a[7] = "cas_thug_2_lemmy";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["cas_thug_2_beards_Body"] ) )
	{
		startIndex = randomint(8);
		level.nextXModel["cas_thug_2_beards_Body"] = startIndex;
	}
	index = level.nextXModel["cas_thug_2_beards_Body"];
	level.nextXModel["cas_thug_2_beards_Body"] = index+1;

	if( level.nextXModel["cas_thug_2_beards_Body"] >= 8 )
		level.nextXModel["cas_thug_2_beards_Body"] = 0;

	if( (index >= 8) || (index < 0))
		index = randomint(8);

	a = main();
	return a[ index ];
}
