// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "cas_thug_5_chin_airport";
	a[1] = "cas_thug_5_goatee_airport";
	a[2] = "cas_thug_5_beard_airport";
	a[3] = "thug_bald";
	a[4] = "cas_thug_5_stache_airport";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["cas_thug_5_beards_airport_Body"] ) )
	{
		startIndex = randomint(5);
		level.nextXModel["cas_thug_5_beards_airport_Body"] = startIndex;
	}
	index = level.nextXModel["cas_thug_5_beards_airport_Body"];
	level.nextXModel["cas_thug_5_beards_airport_Body"] = index+1;

	if( level.nextXModel["cas_thug_5_beards_airport_Body"] >= 5 )
		level.nextXModel["cas_thug_5_beards_airport_Body"] = 0;

	if( (index >= 5) || (index < 0))
		index = randomint(5);

	a = main();
	return a[ index ];
}
