// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "cas_thug_1_body_airport";
	a[1] = "cas_thug_2_body_maroon_airport";
	a[2] = "cas_thug_3_body_airport";
	a[3] = "cas_thug_1_body_black_airport";
	a[4] = "cas_thug_3_body_bars_airport";
	a[5] = "cas_thug_1_body_blue_airport";
	a[6] = "cas_thug_3_body_black_airport";
	a[7] = "cas_thug_1_body_brown_airport";
	a[8] = "cas_thug_3_body_blue_airport";
	a[9] = "cas_thug_2_body_airport";
	a[10] = "cas_thug_3_body_red_airport";
	a[11] = "cas_thug_1_body_green_airport";
	a[12] = "cas_thug_3_body_brown_airport";
	a[13] = "cas_thug_1_body_lavender_airport";
	a[14] = "cas_thug_3_body_green_airport";
	a[15] = "cas_thug_3_body_tan_airport";
	a[16] = "cas_thug_3_body_yellow_airport";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["cas_thug_bodies_airport_Body"] ) )
	{
		startIndex = randomint(17);
		level.nextXModel["cas_thug_bodies_airport_Body"] = startIndex;
	}
	index = level.nextXModel["cas_thug_bodies_airport_Body"];
	level.nextXModel["cas_thug_bodies_airport_Body"] = index+1;

	if( level.nextXModel["cas_thug_bodies_airport_Body"] >= 17 )
		level.nextXModel["cas_thug_bodies_airport_Body"] = 0;

	if( (index >= 17) || (index < 0))
		index = randomint(17);

	a = main();
	return a[ index ];
}
