// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "casino_male_2_body";
	a[1] = "casino_male_2_body_red";
	a[2] = "casino_male_1_body";
	a[3] = "casino_male_2_body_white";
	a[4] = "casino_male_1_body";
	a[5] = "casino_male_2_body_purple";
	a[6] = "casino_male_1_body";
	a[7] = "casino_male_2_body_navy";
	a[8] = "casino_male_1_body";
	a[9] = "casino_male_2_body_green";
	a[10] = "casino_male_1_body";
	a[11] = "casino_male_1_body";
	a[12] = "casino_male_2_body_red";
	a[13] = "casino_male_2_body_navy";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["casino_male_bodies_Body"] ) )
	{
		startIndex = randomint(14);
		level.nextXModel["casino_male_bodies_Body"] = startIndex;
	}
	index = level.nextXModel["casino_male_bodies_Body"];
	level.nextXModel["casino_male_bodies_Body"] = index+1;

	if( level.nextXModel["casino_male_bodies_Body"] >= 14 )
		level.nextXModel["casino_male_bodies_Body"] = 0;

	if( (index >= 14) || (index < 0))
		index = randomint(14);

	a = main();
	return a[ index ];
}
