// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "eco_soldier_body_tan_camo";
	a[1] = "eco_soldier_body";
	a[2] = "eco_soldier_body_tan_camo";
	a[3] = "eco_soldier_body_camo";
	a[4] = "eco_soldier_body_tan";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["eco_soldier_bodies_Body"] ) )
	{
		startIndex = randomint(5);
		level.nextXModel["eco_soldier_bodies_Body"] = startIndex;
	}
	index = level.nextXModel["eco_soldier_bodies_Body"];
	level.nextXModel["eco_soldier_bodies_Body"] = index+1;

	if( level.nextXModel["eco_soldier_bodies_Body"] >= 5 )
		level.nextXModel["eco_soldier_bodies_Body"] = 0;

	if( (index >= 5) || (index < 0))
		index = randomint(5);

	a = main();
	return a[ index ];
}
