// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "fem_civ_1_body";
	a[1] = "fem_civ_2_body";
	a[2] = "fem_civ_1_body_blue";
	a[3] = "fem_civ_2_body_tan";
	a[4] = "fem_civ_1_body_red";
	a[5] = "fem_civ_2_body_green";
	a[6] = "fem_civ_1_body_yellow";
	a[7] = "fem_civ_2_body_tan";
	a[8] = "fem_civ_1_body_pink";
	a[9] = "fem_civ_1_body_lime";
	a[10] = "fem_civ_1_body_purple";
	a[11] = "fem_civ_1_body_tan";
	a[12] = "fem_civ_1_body_green";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["female_civilian_bodies_Body"] ) )
	{
		startIndex = randomint(13);
		level.nextXModel["female_civilian_bodies_Body"] = startIndex;
	}
	index = level.nextXModel["female_civilian_bodies_Body"];
	level.nextXModel["female_civilian_bodies_Body"] = index+1;

	if( level.nextXModel["female_civilian_bodies_Body"] >= 13 )
		level.nextXModel["female_civilian_bodies_Body"] = 0;

	if( (index >= 13) || (index < 0))
		index = randomint(13);

	a = main();
	return a[ index ];
}
