// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "mp_mi6_body_2";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["mp_mi6_bodies_C1_Body"] ) )
	{
		startIndex = randomint(1);
		level.nextXModel["mp_mi6_bodies_C1_Body"] = startIndex;
	}
	index = level.nextXModel["mp_mi6_bodies_C1_Body"];
	level.nextXModel["mp_mi6_bodies_C1_Body"] = index+1;

	if( level.nextXModel["mp_mi6_bodies_C1_Body"] >= 1 )
		level.nextXModel["mp_mi6_bodies_C1_Body"] = 0;

	if( (index >= 1) || (index < 0))
		index = randomint(1);

	a = main();
	return a[ index ];
}
