// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "mp_mi6_head_1";
	a[1] = "mp_henchmen_01_head";
	a[2] = "mp_mi6_head_1";
	a[3] = "mp_henchmen_01_head";
	a[4] = "mp_mi6_head_1";
	a[5] = "mp_henchmen_01_head";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["mp_mi6_heads_C1_Body"] ) )
	{
		startIndex = randomint(6);
		level.nextXModel["mp_mi6_heads_C1_Body"] = startIndex;
	}
	index = level.nextXModel["mp_mi6_heads_C1_Body"];
	level.nextXModel["mp_mi6_heads_C1_Body"] = index+1;

	if( level.nextXModel["mp_mi6_heads_C1_Body"] >= 6 )
		level.nextXModel["mp_mi6_heads_C1_Body"] = 0;

	if( (index >= 6) || (index < 0))
		index = randomint(6);

	a = main();
	return a[ index ];
}
