// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "mp_henchmen_01_body";
	a[1] = "mp_henchmen_04_body";
	a[2] = "mp_henchmen_03_body";
	a[3] = "mp_henchmen_05_body";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["mp_quantum_bodies_B2_Body"] ) )
	{
		startIndex = randomint(4);
		level.nextXModel["mp_quantum_bodies_B2_Body"] = startIndex;
	}
	index = level.nextXModel["mp_quantum_bodies_B2_Body"];
	level.nextXModel["mp_quantum_bodies_B2_Body"] = index+1;

	if( level.nextXModel["mp_quantum_bodies_B2_Body"] >= 4 )
		level.nextXModel["mp_quantum_bodies_B2_Body"] = 0;

	if( (index >= 4) || (index < 0))
		index = randomint(4);

	a = main();
	return a[ index ];
}
