// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "obanno_henchman_01_body";
	a[1] = "obanno_henchman_02_body";
	a[2] = "obanno_henchman_03_body";
	a[3] = "obanno_henchman_02_body_olive";
	a[4] = "obanno_henchman_02_body_blue";
	a[5] = "obanno_henchman_02_body_green";
	a[6] = "obanno_henchman_01_body_blue";
	a[7] = "obanno_henchman_03_body_olivepants";
	a[8] = "obanno_henchman_01_body_yellow";
	a[9] = "obanno_henchman_01_body_bluevest";
	a[10] = "obanno_henchman_03_body_navy";
	a[11] = "obanno_henchman_01_body_red";
	a[12] = "obanno_henchman_02_body_orange";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["obanno_henchman_bodies_Body"] ) )
	{
		startIndex = randomint(13);
		level.nextXModel["obanno_henchman_bodies_Body"] = startIndex;
	}
	index = level.nextXModel["obanno_henchman_bodies_Body"];
	level.nextXModel["obanno_henchman_bodies_Body"] = index+1;

	if( level.nextXModel["obanno_henchman_bodies_Body"] >= 13 )
		level.nextXModel["obanno_henchman_bodies_Body"] = 0;

	if( (index >= 13) || (index < 0))
		index = randomint(13);

	a = main();
	return a[ index ];
}
