// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "tourist_3_facial_beard";
	a[1] = "tourist_3_facial_glasses_5";
	a[2] = "thug_bald";
	a[3] = "tourist_3_facial_beard_glasses_6";
	a[4] = "tourist_3_facial_glasses_4";
	a[5] = "tourist_3_facial_beard_glasses_5";
	a[6] = "tourist_3_facial_glasses_6";
	a[7] = "tourist_3_facial_beard_glasses_4";
	return a;
}


getnextmodel()
{
	if( !isdefined( level.nextXModel ) )
	{
		level.nextXModel = [];
	}

	if( !isdefined( level.nextXModel["tourist_3_facials_Body"] ) )
	{
		startIndex = randomint(8);
		level.nextXModel["tourist_3_facials_Body"] = startIndex;
	}
	index = level.nextXModel["tourist_3_facials_Body"];
	level.nextXModel["tourist_3_facials_Body"] = index+1;

	if( level.nextXModel["tourist_3_facials_Body"] >= 8 )
		level.nextXModel["tourist_3_facials_Body"] = 0;

	if( (index >= 8) || (index < 0))
		index = randomint(8);

	a = main();
	return a[ index ];
}
