// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("semiformal_female_03_complete_opera");
	self.voice = "american";
}

precache()
{
	precacheModel("semiformal_female_03_complete_opera");
}
