// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("bond_opera_body");
	self attach("bond_opera_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("bond_opera_body");
	precacheModel("bond_opera_head");
}
