// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\mi6_agent_bodies::getnextmodel();
	self setModel( body );
	self attach("mi6_agent_1_head", "", false);
	hatModel = xmodelalias\mi6_agent_1_facial::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mi6_agent_bodies::main());
	precacheModel("mi6_agent_1_head");
	codescripts\character::precacheModelArray(xmodelalias\mi6_agent_1_facial::main());
}
