// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("casino_male_2_body_opera");
	self attach("casino_male_2_head_opera", "", false);
	self attach("hands_white_1_low_lod", "", false);
	hatModel = xmodelalias\casino_male_2_facial::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	precacheModel("casino_male_2_body_opera");
	precacheModel("casino_male_2_head_opera");
	precacheModel("hands_white_1_low_lod");
	codescripts\character::precacheModelArray(xmodelalias\casino_male_2_facial::main());
}
