// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_bond_body");
	self attach("mp_bond_head", "", false);
}

precache()
{
	precacheModel("mp_bond_body");
	precacheModel("mp_bond_head");
}
