// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\female_civilian_bodies::getnextmodel();
	self setModel( body );
	self attach("fem_civ_2_head", "", false);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\female_civilian_bodies::main());
	precacheModel("fem_civ_2_head");
}
