// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\lc_thug_bodies_SC_B::getnextmodel();
	self setModel( body );
	self attach("lc_thug_2_head_sienna", "", false);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\lc_thug_bodies_SC_B::main());
	precacheModel("lc_thug_2_head_sienna");
}
