// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\tourist_train_bodies::getnextmodel();
	self setModel( body );
	self attach("head_tourist_1_kent_venice", "", false);
	hatModel = xmodelalias\tourist_1_facials::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\tourist_train_bodies::main());
	precacheModel("head_tourist_1_kent_venice");
	codescripts\character::precacheModelArray(xmodelalias\tourist_1_facials::main());
}
