// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\tourist_train_bodies::getnextmodel();
	self setModel( body );
	self attach("embassy_worker_03_head_dave", "", false);
	hatModel = xmodelalias\embassy_worker_03_facial::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\tourist_train_bodies::main());
	precacheModel("embassy_worker_03_head_dave");
	codescripts\character::precacheModelArray(xmodelalias\embassy_worker_03_facial::main());
}
