// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("getler_body");
	self attach("getler_head", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("getler_body");
	precacheModel("getler_head");
}
