// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("casino_female_02_red");
	self attach("thug_bald", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("casino_female_02_red");
	precacheModel("thug_bald");
}
