// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("casino_male_2_body_white_opera");
	self attach("casino_male_3_head_opera", "", false);
	self attach("hands_white_1_low_lod", "", false);
	self.voice = "american";
}

precache()
{
	precacheModel("casino_male_2_body_white_opera");
	precacheModel("casino_male_3_head_opera");
	precacheModel("hands_white_1_low_lod");
}
