// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	body = xmodelalias\cas_thug_bodies::getnextmodel();
	self setModel( body );
	self attach("cas_thug_5_head", "", false);
	hatModel = xmodelalias\cas_thug_5_beards::getnextmodel();
	self.hatModel = hatModel;
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\cas_thug_bodies::main());
	precacheModel("cas_thug_5_head");
	codescripts\character::precacheModelArray(xmodelalias\cas_thug_5_beards::main());
}
