// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_jap_impinf2_head1_1";
	a[1] = "char_jap_impinf2_head1_2";
	a[2] = "char_jap_impinf2_head1_3";
	a[3] = "char_jap_impinf2_head2_1";
	a[4] = "char_jap_impinf2_head2_2";
	a[5] = "char_jap_impinf2_head2_3";
	a[6] = "char_jap_impinf2_head3_1";
	a[7] = "char_jap_impinf2_head3_2";
	a[8] = "char_jap_impinf2_head3_3";
	return a;
}
