// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\c_afr_mpla_drone_rigid_wgun_als::main());
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\c_afr_mpla_drone_rigid_wgun_als::main());
}
