// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\c_afg_muhaj_body2_als::main());
	self.headModel = codescripts\character::randomElement(xmodelalias\c_afg_muhaj_body2_head_als::main());
	self attach(self.headModel, "", true);
	self.gearModel = codescripts\character::randomElement(xmodelalias\c_afg_muhaj_body2_gear_als::main());
	self attach(self.gearModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\c_afg_muhaj_body2_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_afg_muhaj_body2_head_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_afg_muhaj_body2_gear_als::main());
}
