// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_chn_afghan_zhao_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_chn_afghan_zhao_fb");
}
