// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_redcross_doctor_body");
	self.headModel = "c_mul_redcross_doctor_head1";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_redcross_doctor_body");
	precacheModel("c_mul_redcross_doctor_head1");
}
