// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_menendez_suit_body_bleed");
	self.headModel = "c_mul_menendez_old_head_bleed";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_menendez_suit_body_bleed");
	precacheModel("c_mul_menendez_old_head_bleed");
}
