// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_jinan_guard_body");
	self.headModel = codescripts\character::randomElement(xmodelalias\c_mul_jinan_guard_head_als::main());
	self attach(self.headModel, "", true);
	self.voice = "terrorist";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_jinan_guard_body");
	codescripts\character::precacheModelArray(xmodelalias\c_mul_jinan_guard_head_als::main());
}
