// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\c_mul_civ_rich_male_asn_upper_als::main());
	self.headModel = "c_mul_civ_club_male_head5";
	self attach(self.headModel, "", true);
	self.hatModel = codescripts\character::randomElement(xmodelalias\c_mul_civ_rich_male_lower_als::main());
	self attach(self.hatModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_male_asn_upper_als::main());
	precacheModel("c_mul_civ_club_male_head5");
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_male_lower_als::main());
}
