// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_neomarx_la_medium_fb");
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_neomarx_la_medium_fb");
}
