// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_pmc_assault_body_3");
	self.headModel = "c_mul_pmc_assault_head";
	self attach(self.headModel, "", true);
	self.hatModel = "c_mul_pmc_helmet_main";
	self attach(self.hatModel);
	self.gearModel = "c_mul_pmc_assault_gear";
	self attach(self.gearModel, "", true);
	self.voice = "pmc";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_pmc_assault_body_3");
	precacheModel("c_mul_pmc_assault_head");
	precacheModel("c_mul_pmc_helmet_main");
	precacheModel("c_mul_pmc_assault_gear");
}
