// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_civ_rich_female_body1_1");
	self.headModel = "c_mul_civ_rich_female_head1";
	self attach(self.headModel, "", true);
	self.hatModel = codescripts\character::randomElement(xmodelalias\c_mul_civ_rich_female_clothes_als::main());
	self attach(self.hatModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_civ_rich_female_body1_1");
	precacheModel("c_mul_civ_rich_female_head1");
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_female_clothes_als::main());
}
