// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\c_mul_civ_rich_male_upper_als::main());
	self.headModel = codescripts\character::randomElement(xmodelalias\c_mul_civ_rich_male_head_als::main());
	self attach(self.headModel, "", true);
	self.hatModel = codescripts\character::randomElement(xmodelalias\c_mul_civ_rich_male_lower_als::main());
	self attach(self.hatModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_male_upper_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_male_head_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_mul_civ_rich_male_lower_als::main());
}
