// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_jinan_it_highres_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_jinan_it_highres_fb");
}
