// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_pan_dingbats_body_1");
	self.headModel = "c_pan_dingbats_head_3_cin";
	self attach(self.headModel, "", true);
	self.hatModel = "c_pan_dingbats_hat_4";
	self attach(self.hatModel);
	self.gearModel = "c_pan_dingbats_gear_1";
	self attach(self.gearModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_pan_dingbats_body_1");
	precacheModel("c_pan_dingbats_head_3_cin");
	precacheModel("c_pan_dingbats_hat_4");
	precacheModel("c_pan_dingbats_gear_1");
}
