// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_lapd_medic_body");
	self.headModel = "c_usa_lapd_medic_head_mask";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_lapd_medic_body");
	precacheModel("c_usa_lapd_medic_head_mask");
}
