// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_navy_body_brn");
	self.headModel = "c_usa_navy_head3";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_navy_body_brn");
	precacheModel("c_usa_navy_head3");
}
