// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_zom_electrician_body");
	self.voice = "german";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_zom_electrician_body");
}
