// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "pnzgren_head1";
	a[1] = "pnzgren_head2";
	a[2] = "pnzgren_head3";
	a[3] = "pnzgren_head4";
	a[4] = "pnzgren_head1_2";
	a[5] = "pnzgren_head1_3";
	a[6] = "pnzgren_head1_4";
	a[7] = "pnzgren_head2_2";
	a[8] = "pnzgren_head2_3";
	a[9] = "pnzgren_head2_4";
	a[10] = "pnzgren_head3_2";
	a[11] = "pnzgren_head3_3";
	a[12] = "pnzgren_head3_4";
	a[13] = "pnzgren_head4_2";
	a[14] = "pnzgren_head4_3";
	a[15] = "pnzgren_head4_4";
	return a;
}
