// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "usinf_head1_1";
	a[1] = "usinf_head1_2";
	a[2] = "usinf_head1_3";
	a[3] = "usinf_head2_1";
	a[4] = "usinf_head2_2";
	a[5] = "usinf_head2_3";
	a[6] = "usinf_head3_1";
	a[7] = "usinf_head3_2";
	a[8] = "usinf_head3_3";
	return a;
}
