//This file is auto-generated by GameStudio. Edit at your own risk.
//destructible computer_01_destp
#include common_scripts\_destructible;
#using_animtree( "destructibles" );

main()
{
	destructible_create( "computer_01_destp", "tag_origin", 200 );
				destructible_fx_spawn_immediate( "tag_fx", "vfx/test/ui_prototype/ui_compscrn_proto", true, undefined, undefined, undefined, 2 );
				destructible_fx( "tag_fx", "vfx/glass/glass_shatter_01", true );
			destructible_state( undefined, "computer_screen_01_dstry_destp", 300 );
			destructible_state(  );
}
