// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_us_ranger_medic_wells");
	self attach("xmodel/head_us_ranger_medic_wells", "", true);
	self.hatModel = "xmodel/helmet_us_ranger_medic_wells";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/character_us_ranger_medic_wells");
	precacheModel("xmodel/head_us_ranger_medic_wells");
	precacheModel("xmodel/helmet_us_ranger_medic_wells");
}
