// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\body_US_Ranger_Wounded::main());
	codescripts\character::attachFromArray(xmodelalias\head_US_Ranger_American::main());
	self.hatModel = "xmodel/helmet_us_ranger_generic";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\body_US_Ranger_Wounded::main());
	codescripts\character::precacheModelArray(xmodelalias\head_US_Ranger_American::main());
	precacheModel("xmodel/helmet_us_ranger_generic");
}
