// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_us_wet_ranger_lt_coffey");
	self attach("xmodel/head_us_ranger_grant", "", true);
	self.hatModel = "xmodel/helmet_us_wet_ranger_generic";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/character_us_wet_ranger_lt_coffey");
	precacheModel("xmodel/head_us_ranger_grant");
	precacheModel("xmodel/helmet_us_wet_ranger_generic");
}
