// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_us_ranger_pvt_c");
	self attach("xmodel/head_us_ranger_harry", "", true);
	self.hatModel = "xmodel/helmet_us_ranger_generic";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("xmodel/character_us_ranger_pvt_c");
	precacheModel("xmodel/head_us_ranger_harry");
	precacheModel("xmodel/helmet_us_ranger_generic");
}
