// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_british_afrca_mac_radio");
	self attach("xmodel/head_british_macgregor", "", true);
	self.hatModel = "xmodel/helmet_british_afrca";
	self attach(self.hatModel);
	self.voice = "british";
}

precache()
{
	precacheModel("xmodel/character_british_afrca_mac_radio");
	precacheModel("xmodel/head_british_macgregor");
	precacheModel("xmodel/helmet_british_afrca");
}
