// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\body_British_Africa_low::main());
	codescripts\character::attachFromArray(xmodelalias\head_british_afrikakorp_low::main());
	self.hatModel = "xmodel/helmet_british_afrca_low";
	self attach(self.hatModel);
	self.voice = "british";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\body_British_Africa_low::main());
	codescripts\character::precacheModelArray(xmodelalias\head_british_afrikakorp_low::main());
	precacheModel("xmodel/helmet_british_afrca_low");
}
