// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_winter_hooded");
	self attach("xmodel/head_german_winter_jon", "", true);
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_winter_hooded");
	precacheModel("xmodel/head_german_winter_jon");
}
