// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_normandy_thin_injured");
	codescripts\character::attachFromArray(xmodelalias\head_german_normandy::main());
	self.hatModel = "xmodel/helmet_german_normandy";
	self attach(self.hatModel);
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_normandy_thin_injured");
	codescripts\character::precacheModelArray(xmodelalias\head_german_normandy::main());
	precacheModel("xmodel/helmet_german_normandy");
}
