// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_normandy_fat");
	codescripts\character::attachFromArray(xmodelalias\head_german_fat::main());
	self.hatModel = "xmodel/helmet_german_normandy_emilio";
	self attach(self.hatModel);
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_normandy_fat");
	codescripts\character::precacheModelArray(xmodelalias\head_german_fat::main());
	precacheModel("xmodel/helmet_german_normandy_emilio");
}
