// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_german_winter_mg42_low");
	self attach("xmodel/head_german_winter_jon_low", "", true);
	self.hatModel = "xmodel/helmet_german_winter_jon";
	self attach(self.hatModel);
	self attach("xmodel/weapon_mg42_carry", "TAG_ORIGIN");
	self.voice = "german";
}

precache()
{
	precacheModel("xmodel/character_german_winter_mg42_low");
	precacheModel("xmodel/head_german_winter_jon_low");
	precacheModel("xmodel/helmet_german_winter_jon");
	precacheModel("xmodel/weapon_mg42_carry");
}
