// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_american_ranger");
	self attach("xmodel/head_us_ranger_preston", "", true);
	self setViewmodel("xmodel/viewmodel_hands_cloth");
}

precache()
{
	precacheModel("xmodel/playerbody_american_ranger");
	precacheModel("xmodel/head_us_ranger_preston");
	precacheModel("xmodel/viewmodel_hands_cloth");
}
