// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\mp_body_british_normandy::main());
	self attach("xmodel/head_british_paul", "", true);
	self.hatModel = "xmodel/helmet_british_normandy";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_british");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mp_body_british_normandy::main());
	precacheModel("xmodel/head_british_paul");
	precacheModel("xmodel/helmet_british_normandy");
	precacheModel("xmodel/viewmodel_hands_british");
}
