// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_british_africa03");
	self attach("xmodel/head_british_macgregor", "", true);
	self.hatModel = "xmodel/helmet_british_afrca";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_british_bare");
}

precache()
{
	precacheModel("xmodel/playerbody_british_africa03");
	precacheModel("xmodel/head_british_macgregor");
	precacheModel("xmodel/helmet_british_afrca");
	precacheModel("xmodel/viewmodel_hands_british_bare");
}
