// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterdark");
	codescripts\character_mp::attachFromArray(xmodelalias\mp_head_german_winterdark::main());
	self.hatModel = "xmodel/helmet_german_winter_dark";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	precacheModel("xmodel/playerbody_german_winterdark");
	codescripts\character::precacheModelArray(xmodelalias\mp_head_german_winterdark::main());
	precacheModel("xmodel/helmet_german_winter_dark");
	precacheModel("xmodel/viewmodel_hands_german_winter");
}
