// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterlight_hooded");
	self attach("xmodel/head_german_winter_jon", "", true);
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	precacheModel("xmodel/playerbody_german_winterlight_hooded");
	precacheModel("xmodel/head_german_winter_jon");
	precacheModel("xmodel/viewmodel_hands_german_winter");
}
