// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterlight");
	self attach("xmodel/head_german_winter_jon", "", true);
	self.hatModel = "xmodel/helmet_german_winter_jon";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	precacheModel("xmodel/playerbody_german_winterlight");
	precacheModel("xmodel/head_german_winter_jon");
	precacheModel("xmodel/helmet_german_winter_jon");
	precacheModel("xmodel/viewmodel_hands_german_winter");
}
