// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_german_winterdark_masked");
	self setViewmodel("xmodel/viewmodel_hands_german_winter");
}

precache()
{
	precacheModel("xmodel/playerbody_german_winterdark_masked");
	precacheModel("xmodel/viewmodel_hands_german_winter");
}
