// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_russian_coat02");
	self attach("xmodel/head_russian_winter_jon", "", true);
	self.hatModel = "xmodel/helmet_russian_padded_b";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	precacheModel("xmodel/playerbody_russian_coat02");
	precacheModel("xmodel/head_russian_winter_jon");
	precacheModel("xmodel/helmet_russian_padded_b");
	precacheModel("xmodel/viewmodel_hands_russian");
}
