// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\mp_body_russian_coat::main());
	codescripts\character_mp::attachFromArray(xmodelalias\mp_head_russian::main());
	self.hatModel = codescripts\character::randomElement(xmodelalias\mp_helmet_russian_coat::main());
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\mp_body_russian_coat::main());
	codescripts\character::precacheModelArray(xmodelalias\mp_head_russian::main());
	codescripts\character::precacheModelArray(xmodelalias\mp_helmet_russian_coat::main());
	precacheModel("xmodel/viewmodel_hands_russian");
}
