// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_russian_coat05");
	self attach("xmodel/head_russian_winter_popov", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_popov_hat";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	precacheModel("xmodel/playerbody_russian_coat05");
	precacheModel("xmodel/head_russian_winter_popov");
	precacheModel("xmodel/helmet_russian_trench_popov_hat");
	precacheModel("xmodel/viewmodel_hands_russian");
}
