// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/playerbody_russian_coat02");
	self attach("xmodel/head_russian_winter_volsky", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_b_hat";
	self attach(self.hatModel, "", true);
	self setViewmodel("xmodel/viewmodel_hands_russian");
}

precache()
{
	precacheModel("xmodel/playerbody_russian_coat02");
	precacheModel("xmodel/head_russian_winter_volsky");
	precacheModel("xmodel/helmet_russian_trench_b_hat");
	precacheModel("xmodel/viewmodel_hands_russian");
}
