// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_russian_trench_a");
	self attach("xmodel/head_russian_winter_dan", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_a_hat";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_russian_trench_a");
	precacheModel("xmodel/head_russian_winter_dan");
	precacheModel("xmodel/helmet_russian_trench_a_hat");
}
