// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_russian_trench_c");
	self attach("xmodel/head_russian_winter_jesse", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_c_hat";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_russian_trench_c");
	precacheModel("xmodel/head_russian_winter_jesse");
	precacheModel("xmodel/helmet_russian_trench_c_hat");
}
