// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_russian_trench_popov");
	self attach("xmodel/head_russian_winter_popov", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_popov_hat";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_russian_trench_popov");
	precacheModel("xmodel/head_russian_winter_popov");
	precacheModel("xmodel/helmet_russian_trench_popov_hat");
}
