// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_russian_trench_b");
	self attach("xmodel/head_russian_winter_volsky", "", true);
	self.hatModel = "xmodel/helmet_russian_trench_b_hat";
	self attach(self.hatModel);
	self.voice = "russian";
}

precache()
{
	precacheModel("xmodel/character_russian_trench_b");
	precacheModel("xmodel/head_russian_winter_volsky");
	precacheModel("xmodel/helmet_russian_trench_b_hat");
}
