// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: class_shotgun
// Convert Time: 07/19/2012 23:09:52
#include common_scripts\utility;

precache()
{
	PrecacheModel( "c_chn_mp_pla_shotgun_fb" );
	PrecacheModel( "c_chn_mp_pla_armorsleeve_viewhands" );

	if ( level.multiTeam )	
	{
		game["set_player_model"]["axis"]["spread"] = ::set_player_model;
	}
	else
	{
		game["set_player_model"]["axis"]["spread"] = ::set_player_model;
	}
}

set_player_model()
{
	self SetModel( "c_chn_mp_pla_shotgun_fb" );
	self SetViewModel( "c_chn_mp_pla_armorsleeve_viewhands" );

	heads = [];
}

