// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: class_assault
// Convert Time: 07/19/2012 22:02:37
#include common_scripts\utility;

precache()
{
	PrecacheModel( "c_usa_mp_fbi_assault_fb" );
	PrecacheModel( "c_usa_mp_fbi_longsleeve_viewhands" );

	if ( level.multiTeam )	
	{
		game["set_player_model"]["team3"]["default"] = ::set_player_model;
	}
	else
	{
		game["set_player_model"]["allies"]["default"] = ::set_player_model;
	}
}

set_player_model()
{
	self SetModel( "c_usa_mp_fbi_assault_fb" );
	self SetViewModel( "c_usa_mp_fbi_longsleeve_viewhands" );

	heads = [];
}

