// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: class_sniper
// Convert Time: 07/19/2012 22:02:38
#include common_scripts\utility;

precache()
{
	PrecacheModel( "c_usa_mp_fbi_sniper_fb" );
	PrecacheModel( "c_usa_mp_fbi_longsleeve_viewhands" );

	if ( level.multiTeam )	
	{
		game["set_player_model"]["team3"]["rifle"] = ::set_player_model;
	}
	else
	{
		game["set_player_model"]["allies"]["rifle"] = ::set_player_model;
	}
}

set_player_model()
{
	self SetModel( "c_usa_mp_fbi_sniper_fb" );
	self SetViewModel( "c_usa_mp_fbi_longsleeve_viewhands" );

	heads = [];
}

