// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_chicken::main();
	common_scripts\_destructible_types_anim_light_fluo_on::main();
	common_scripts\_destructible_types_anim_wallfan::main();
}
