// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\com_roofvent2::main();
	maps\animated_models\foliage_tree_river_birch_lg_a_sway::main();
	maps\animated_models\foliage_tree_river_birch_xl_a::main();
}
