// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_wallfan::main();
	maps\animated_models\foliage_cod5_tree_jungle_03::main();
	maps\animated_models\foliage_pacific_bushtree02::main();
	maps\animated_models\foliage_pacific_palms08::main();
	maps\animated_models\hanging_apron_wind_medium::main();
	maps\animated_models\hanging_longsleeve_wind_medium::main();
	maps\animated_models\hanging_sheet_wind_medium::main();
	maps\animated_models\hanging_shortsleeve_wind_medium::main();
}
