// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: class_sniper
// Convert Time: 11/12/2011 14:30:29
#include common_scripts\utility;

precache()
{
	PrecacheModel( "c_usa_mp_sealteam6_sniper_body" );
	PrecacheModel( "c_usa_mp_sealteam6_assault_viewhands" );
	PrecacheModel( "c_usa_mp_sealteam6_sniper_head1" );
	PrecacheModel( "c_usa_mp_sealteam6_sniper_head2" );
	PrecacheModel( "c_usa_mp_sealteam6_sniper_head3" );

	game["set_player_model"]["allies"]["rifle"] = ::set_player_model;
}

set_player_model()
{
	self SetModel( "c_usa_mp_sealteam6_sniper_body" );
	self SetViewModel( "c_usa_mp_sealteam6_assault_viewhands" );

	heads = [];
	heads[ 0 ] = "c_usa_mp_sealteam6_sniper_head1";
	heads[ 1 ] = "c_usa_mp_sealteam6_sniper_head2";
	heads[ 2 ] = "c_usa_mp_sealteam6_sniper_head3";

	head = random( heads );
	self Attach( head, "", true );
}

