// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character_mp::setModelFromArray(xmodelalias\bodies_complete_mp_spetsnaz::main());
	self setViewmodel("viewmodel_base_viewhands");
}

precache()
{
	codescripts\character_mp::precacheModelArray(xmodelalias\bodies_complete_mp_spetsnaz::main());
	precacheModel("viewmodel_base_viewhands");
}
