// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	codescripts\character::setModelFromArray(xmodelalias\pnzgren_bodyalias::main());
	codescripts\character::attachFromArray(xmodelalias\pnzgren_headalias::main());
	self.hatModel = codescripts\character::randomElement(xmodelalias\pnzgren_helmalias::main());
	self attach(self.hatModel, "", true);
	self.voice = "american";
}

precache()
{
	codescripts\character::precacheModelArray(xmodelalias\pnzgren_bodyalias::main());
	codescripts\character::precacheModelArray(xmodelalias\pnzgren_headalias::main());
	codescripts\character::precacheModelArray(xmodelalias\pnzgren_helmalias::main());
}
