// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_burke_pmc");
	self attach("head_hero_burke_c", "", true);
	self.headModel = "head_hero_burke_c";
	self.voice = "xslice";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_hero_burke_pmc");
	precacheModel("head_hero_burke_c");
}
