// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_fullbody_opforce_juggernaut");
	self setViewmodel("viewhands_juggernaut_opforce");
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_fullbody_opforce_juggernaut");
	precacheModel("viewhands_juggernaut_opforce");
}
