// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_burke_pmc");
	codescripts\character::attachHead( "alias_pmc_helmet_heads", xmodelalias\alias_pmc_helmet_heads::main() );
	self.voice = "xslice";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("body_hero_burke_pmc");
	codescripts\character::precacheModelArray(xmodelalias\alias_pmc_helmet_heads::main());
}
