// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_ally_pmc_sniper");
	self setViewmodel("viewhands_pmc");
	self.voice = "taskforce";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_ally_pmc_sniper");
	precacheModel("viewhands_pmc");
}
