// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_ghillie_africa_militia_sniper");
	self attach("head_ghillie_africa_militia_sniper", "", true);
	self.headModel = "head_ghillie_africa_militia_sniper";
	self setViewmodel("viewhands_african_militia");
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_opforce_ghillie_africa_militia_sniper");
	precacheModel("head_ghillie_africa_militia_sniper");
	precacheModel("viewhands_african_militia");
}
