// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_henchmen_sniper");
	self attach("head_opforce_henchmen_sniper", "", true);
	self.headModel = "head_opforce_henchmen_sniper";
	self setViewmodel("viewhands_henchmen");
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_opforce_henchmen_sniper");
	precacheModel("head_opforce_henchmen_sniper");
	precacheModel("viewhands_henchmen");
}
