// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_ghillie_arctic_sniper");
	self attach("head_opforce_russian_arctic_sniper", "", true);
	self.headModel = "head_opforce_russian_arctic_sniper";
	self setViewmodel("viewhands_iw5_ghillie_arctic");
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_opforce_ghillie_arctic_sniper");
	precacheModel("head_opforce_russian_arctic_sniper");
	precacheModel("viewhands_iw5_ghillie_arctic");
}
