// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_gign_paris_lmg");
	self attach("head_gign_d", "", true);
	self.headModel = "head_gign_d";
	self setViewmodel("viewhands_sas");
	self.voice = "french";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_gign_paris_lmg");
	precacheModel("head_gign_d");
	precacheModel("viewhands_sas");
}
