// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_russian_air_sniper");
	self attach("head_opforce_russian_air_sniper", "", true);
	self.headModel = "head_opforce_russian_air_sniper";
	self setViewmodel("viewhands_russian_b");
	self.voice = "russian";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_opforce_russian_air_sniper");
	precacheModel("head_opforce_russian_air_sniper");
	precacheModel("viewhands_russian_b");
}
