// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_ally_delta_sniper");
	self attach("head_ally_delta_sniper", "", true);
	self.headModel = "head_ally_delta_sniper";
	self setViewmodel("viewhands_delta");
	self.voice = "delta";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_ally_delta_sniper");
	precacheModel("head_ally_delta_sniper");
	precacheModel("viewhands_delta");
}
