// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_gign_paris_smg");
	self attach("head_gign_saber_gasmask", "", true);
	self.headModel = "head_gign_saber_gasmask";
	self setViewmodel("viewhands_sas");
	self.voice = "french";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_gign_paris_smg");
	precacheModel("head_gign_saber_gasmask");
	precacheModel("viewhands_sas");
}
