// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_cloak_test");
	self attach("mp_head_cloak_test", "", true);
	self.headModel = "mp_head_cloak_test";
	self setViewmodel("mp_viewhands_cloak_test");
	self.voice = "american";
	self SetClothType("vestlight");
}

precache()
{
	precacheModel("mp_body_cloak_test");
	precacheModel("mp_head_cloak_test");
	precacheModel("mp_viewhands_cloak_test");
}
