// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_a10_warthog::main( "vehicle_a10_warthog", undefined, "script_vehicle_a10_warthog" );
	vehicle_scripts\_apache::main( "vehicle_apache", undefined, "script_vehicle_apache_berlin" );
	vehicle_scripts\_hind::main( "vehicle_mi24p_hind_woodland", undefined, "script_vehicle_hind_woodland" );
	vehicle_scripts\_leopard_2a7::main( "vehicle_leopard_2a7", undefined, "script_vehicle_leopard_2a7" );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_bench", undefined, "script_vehicle_littlebird_bench" );
	vehicle_scripts\_littlebird_player::main( "vehicle_little_bird_bench", undefined, "script_vehicle_littlebird_player" );
	vehicle_scripts\_hind::main( "vehicle_ny_harbor_hind", "ny_harbor_hind", "script_vehicle_ny_harbor_hind", true );  // use the turret weapon
	vehicle_scripts\_t90::main( "vehicle_t90_tank_woodland", "t90_berlin", "script_vehicle_t90_tank_woodland_berlin" );
	maps\animated_models\fence_tarp_108x76_med_01::main();
}
