// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_btr80::main( "vehicle_btr80", undefined, "script_vehicle_btr80" );
	vehicle_scripts\_btr80::main( "vehicle_btr80", "btr80_physics", "script_vehicle_btr80_physics" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly", undefined, "script_vehicle_mi17_woodland_fly" );
	vehicle_scripts\_uaz_castle::main( "vehicle_uaz_open_player_ride", "uaz", "script_vehicle_uaz_castle" );
	common_scripts\_destructible_types_anim_chicken::main();
	common_scripts\_destructible_types_anim_generator::main();
}
