// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_apache::main( "vehicle_apache", undefined, "script_vehicle_apache_mg" );
	vehicle_scripts\_blackhawk_hamburg::main( "vehicle_blackhawk_hero_hamburg", undefined, "script_vehicle_blackhawk_hero_hamburg" );
	vehicle_scripts\_blackhawk::main( "vehicle_blackhawk_low", undefined, "script_vehicle_blackhawk_low" );
	vehicle_scripts\_f15::main( "vehicle_f15", undefined, "script_vehicle_f15" );
	vehicle_scripts\_gaz::main( "vehicle_gaz_tigr_harbor", undefined, "script_vehicle_gaz_tigr_harbor" );
	vehicle_scripts\_hovercraft::main( "vehicle_hovercraft", undefined, "script_vehicle_hovercraft" );
	vehicle_scripts\_hovercraft_cheap::main( "vehicle_hovercraft", undefined, "script_vehicle_hovercraft_cheap" );
	vehicle_scripts\_m1a1_minigun::main( "vehicle_m1a1_abrams_minigun", undefined, "script_vehicle_m1a1_abrams_minigun" );
	vehicle_scripts\_m1a1_minigun::main( "vehicle_m1a1_abrams_viewmodel", "m1a1_player_tm", "script_vehicle_m1a1_abrams_player_tm" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly_cheap", undefined, "script_vehicle_mi17_woodland_fly_cheap" );
	vehicle_scripts\_mi28::main( "vehicle_mi-28_flying", undefined, "script_vehicle_mi28_flying" );
	vehicle_scripts\_osprey::main( "vehicle_v22_osprey_fly",undefined, "script_vehicle_osprey_fly" );
	vehicle_scripts\_t90::main( "vehicle_t90_tank_woodland", undefined, "script_vehicle_t90_tank_woodland_hamburg" );
}
