// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_gaz::main( "vehicle_gaz_tigr_harbor", "gaz_tigr_hijack", "script_vehicle_gaz_tigr_hijack" );
	vehicle_scripts\_gaz::main( "vehicle_gaz_tigr_base", "gaz_tigr_turret_hijack", "script_vehicle_gaz_tigr_turret_hijack" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_landing", undefined, "script_vehicle_mi17_woodland_landing" );
	vehicle_scripts\_mig29::main( "vehicle_mig29", undefined, "script_vehicle_mig29" );
}
