// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_80s_hatch1::main( "vehicle_80s_hatch1_brn_destructible_mp", undefined, "script_vehicle_80s_hatch1_brn_destructible_mp" );
	vehicle_scripts\_80s_sedan1::main( "vehicle_80s_sedan1_brn", undefined, "script_vehicle_80s_sedan1_brn" );
	vehicle_scripts\_dozor::main( "russian_dozor_600", undefined, "script_vehicle_dozor" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly", undefined, "script_vehicle_mi17_woodland_fly" );
	vehicle_scripts\_mi17_noai::main( "vehicle_mi17_woodland_fly_cheap", undefined, "script_vehicle_mi17_woodland_fly_cheap_noai" );
	vehicle_scripts\_mi28::main( "vehicle_mi-28_flying", undefined, "script_vehicle_mi28_flying" );
	vehicle_scripts\_ugv::main( "vehicle_ugv_robot_viewmodel", undefined, "script_vehicle_ugv_robot" );
	common_scripts\_destructible_types_anim_generator::main();
	common_scripts\_destructible_types_anim_me_fanceil1_spin::main();
	maps\animated_models\fence_tarp_107x56_med_01::main();
	maps\animated_models\fence_tarp_167x56_med_01::main();
	maps\animated_models\hanging_apron_wind_medium::main();
	maps\animated_models\hanging_longsleeve_wind_medium::main();
	maps\animated_models\hanging_sheet_wind_medium::main();
	maps\animated_models\hanging_shortsleeve_wind_medium::main();
}
