// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_submarine_sdv::main( "vehicle_blackshadow_730", undefined, "script_vehicle_blackshadow" );
	vehicle_scripts\_submarine_sdv::main( "vehicle_blackshadow_730_viewmodel", undefined, "script_vehicle_blackshadow_player" );
	vehicle_scripts\_seaknight::main( "ch_46E_ny_harbor", undefined, "script_vehicle_ch46e_ny_harbor" );
	vehicle_scripts\_f15::main( "vehicle_f15", undefined, "script_vehicle_f15" );
	vehicle_scripts\_hind::main( "vehicle_mi24p_hind_woodland", undefined, "script_vehicle_mi24p_hind_woodland" );
	vehicle_scripts\_submarine_nuclear::main( "vehicle_russian_oscar2_sub", undefined, "script_vehicle_russian_submarine" );
	vehicle_scripts\_ss_n_12::main( "vehicle_s300_pmu2", undefined, "script_vehicle_s300_pmu2" );
	vehicle_scripts\_ss_n_12::main( "ss_n_12_missile", undefined, "script_vehicle_ss_n_12" );
	vehicle_scripts\_super_dvora::main( "vehicle_russian_super_dvora_mark2", undefined, "script_vehicle_super_dvora", "50cal_turret_technical" );
	vehicle_scripts\_super_dvora::main( "vehicle_russian_super_dvora_mark2", undefined, "script_vehicle_super_dvora_slowmo", "50cal_turret_technical_slomo" );
	vehicle_scripts\_zodiac::main( "vehicle_zodiac", undefined, "script_vehicle_zodiac" );
	vehicle_scripts\_zodiac::main( "vehicle_zodiac","zodiac_physics", "script_vehicle_zodiac_physics" );
	vehicle_scripts\_zodiac_player::main( "vehicle_zodiac_boat", "zodiac_player_harbor", "script_vehicle_zodiac_player_harbor" );

}
