// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_a10_warthog::main( "vehicle_a10_warthog", undefined, "script_vehicle_a10_warthog" );
	vehicle_scripts\_ac130::main( "tag_origin", undefined, "script_vehicle_ac130" );
	vehicle_scripts\_blackhawk::main( "vehicle_blackhawk", undefined, "script_vehicle_blackhawk" );
	vehicle_scripts\_bm21_troops::main( "vehicle_bm21_mobile_bed", undefined, "script_vehicle_bm21_mobile_bed_troops" );
	vehicle_scripts\_bm21_troops::main( "vehicle_bm21_mobile_cover", undefined, "script_vehicle_bm21_mobile_cover_troops" ); 
	vehicle_scripts\_btr80::main( "vehicle_btr80_low", undefined, "script_vehicle_btr80_ac130" );
	vehicle_scripts\_c130::main( "vehicle_ac130_low",undefined, "script_vehicle_c130" );
	vehicle_scripts\_seaknight::main( "vehicle_ch46e_low", undefined, "script_vehicle_ch46e_low" );
	vehicle_scripts\_f15::main( "vehicle_f15_low", undefined, "script_vehicle_f15_low" );
	vehicle_scripts\_gaz::main( "vehicle_gaz_tigr_base", "gaz_tigr_turret_physics", "script_vehicle_gaz_tigr_turret_physics" );
	vehicle_scripts\_hind::main( "vehicle_mi24p_hind_chernobyl", undefined, "script_vehicle_hind_chernobyl" );
	vehicle_scripts\_humvee::main( "vehicle_hummer", undefined, "script_vehicle_hummer" );
	vehicle_scripts\_hummer_minigun::main( "vehicle_hummer", undefined, "script_vehicle_hummer_minigun_ac130", "minigun_hummer_ac130" );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_bench", undefined, "script_vehicle_littlebird_bench" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly", undefined, "script_vehicle_mi17_woodland_fly" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly_cheap", undefined, "script_vehicle_mi17_woodland_fly_cheap" );
	vehicle_scripts\_mig29::main( "vehicle_mig29_low", undefined, "script_vehicle_mig29_low" );
	vehicle_scripts\_t72::main( "vehicle_t72_tank", undefined, "script_vehicle_t72_tank" );
	vehicle_scripts\_t72_ac130::main( "vehicle_t72_tank", undefined, "script_vehicle_t72_tank_ac130" );
	common_scripts\_destructible_types_anim_building_collapse::main();
	common_scripts\_destructible_types_anim_prop_barge_a::main();
	common_scripts\_destructible_types_anim_prop_missile_boat_a::main();
	common_scripts\_destructible_types_anim_prop_radar_maz::main();
}
