// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_btr80::main( "vehicle_btr80", undefined, "script_vehicle_btr80" );
	vehicle_scripts\_btr80::main( "vehicle_btr80", "btr80_physics", "script_vehicle_btr80_physics" );
	vehicle_scripts\_cobra::main( "vehicle_cobra_helicopter_fly", undefined, "script_vehicle_cobra_helicopter_fly" );
	vehicle_scripts\_mi28::main( "vehicle_mi-28_flying", undefined, "script_vehicle_mi28_flying" );
	vehicle_scripts\_suburban::main( "vehicle_suburban", undefined, "script_vehicle_suburban" );
	vehicle_scripts\_uaz::main( "vehicle_uaz_hardtop", undefined, "script_vehicle_uaz_hardtop" );
	vehicle_scripts\_uaz::main( "vehicle_uaz_hardtop", "uaz_physics", "script_vehicle_uaz_hardtop_physics" );
}
