// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_blackhawk::main( "vehicle_blackhawk", undefined, "script_vehicle_blackhawk" );
	vehicle_scripts\_blackhawk::main( "vehicle_blackhawk_hero_sas_night", undefined, "script_vehicle_blackhawk_hero_sas_night" );
	vehicle_scripts\_hind::main( "vehicle_mi24p_hind_chernobyl", undefined, "script_vehicle_hind_chernobyl" );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_armed", undefined, "script_vehicle_littlebird_armed" );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_bench", undefined, "script_vehicle_littlebird_bench" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly_cheap", undefined, "script_vehicle_mi17_woodland_fly_cheap" );
	vehicle_scripts\_snowmobile::main( "vehicle_snowmobile", undefined, "script_vehicle_snowmobile" );
	vehicle_scripts\_suburban::main( "vehicle_suburban", undefined, "script_vehicle_suburban" );
	vehicle_scripts\_suburban_minigun::main( "vehicle_suburban_technical", undefined, "script_vehicle_suburban_minigun_technical" );
	vehicle_scripts\_ucav::main( "vehicle_ucav", undefined, "script_vehicle_ucav" );
	common_scripts\_destructible_types_anim_generator::main();
	common_scripts\_destructible_types_anim_light_fluo_on::main();
	common_scripts\_destructible_types_anim_light_fluo_single::main();
	common_scripts\_destructible_types_anim_lockers::main();
	common_scripts\_destructible_types_anim_snowmobile::main();
	common_scripts\_destructible_types_anim_wallfan::main();
	maps\animated_models\fence_tarp_130x82_a_med_01::main();
	maps\animated_models\fence_tarp_192x84_a_med_01::main();
	maps\animated_models\fence_tarp_196x146_med_01::main();
	maps\animated_models\highrise_fencetarp_03::main();
}
