// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_blackhawk::main( "vehicle_blackhawk", "blackhawk_so", "script_vehicle_blackhawk_so" );
	vehicle_scripts\_cobra::main( "vehicle_cobra_helicopter", undefined, "script_vehicle_cobra_helicopter_so"  );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_armed", "littlebird_so", "script_vehicle_littlebird_armed_so" );
}
