// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_gaz::main( "vehicle_gaz_tigr_paris", "gaz_tigr_turret_physics_paris", "script_vehicle_gaz_tigr_turret_physics_paris" );
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_bench", undefined, "script_vehicle_littlebird_bench" );
	vehicle_scripts\_mi17::main( "vehicle_mi17_woodland_fly", undefined, "script_vehicle_mi17_woodland_fly" );
	common_scripts\_destructible_types_anim_me_fanceil1_spin::main();
	common_scripts\_destructible_types_anim_motorcycle_01::main();
	maps\animated_models\foliage_paris_tree_plane_medium::main();
}
