// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_littlebird::main( "vehicle_little_bird_armed", "littlebird_so", "script_vehicle_littlebird_armed_so" );
}
