// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	vehicle_scripts\_russian_torpedo::main( "russian_torpedo", undefined, "script_vehicle_russian_torpedo" );
	vehicle_scripts\_zubr::main( "russian_zubr_watercraft", undefined, "script_vehicle_zubr" );
}
