// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_secserv_heavy::main();
	self._aitype = "Ally_SStactical_Heavy_SMG_Base";
}

precache(ai_index)
{
	character\clientscripts\c_usa_secserv_heavy::precache();

	UseFootstepTable(ai_index, "default_ai");
}
