// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_usa_navy_1::main();
			break;
		case 1:
			character\clientscripts\c_usa_navy_2::main();
			break;
		case 2:
			character\clientscripts\c_usa_navy_3::main();
			break;
		case 3:
			character\clientscripts\c_usa_navy_4::main();
			break;
	}

	self._aitype = "Ally_Navy_Blackout_Assault_Base";
}

precache(ai_index)
{
	character\clientscripts\c_usa_navy_1::precache();
	character\clientscripts\c_usa_navy_2::precache();
	character\clientscripts\c_usa_navy_3::precache();
	character\clientscripts\c_usa_navy_4::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
