// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_mul_jinan_guard::main();
			break;
		case 1:
			character\clientscripts\c_mul_jinan_guard_1::main();
			break;
		case 2:
			character\clientscripts\c_mul_jinan_guard_2::main();
			break;
		case 3:
			character\clientscripts\c_mul_jinan_guard_3::main();
			break;
	}

	self._aitype = "Ally_Navy_Blackout_Sniper_Base";
}

precache(ai_index)
{
	character\clientscripts\c_mul_jinan_guard::precache();
	character\clientscripts\c_mul_jinan_guard_1::precache();
	character\clientscripts\c_mul_jinan_guard_2::precache();
	character\clientscripts\c_mul_jinan_guard_3::precache();

	UseFootstepTable(ai_index, "default_ai");
}
