// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\character_sp_german_sheperd_dog::main();
	self._aitype = "ally_dog_sp";
}

precache(ai_index)
{
	character\clientscripts\character_sp_german_sheperd_dog::precache();

	UseFootstepTable(ai_index, "fly_step_dog");
}
