// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_mul_civ_club_short_dress1::main();
			break;
		case 1:
			character\clientscripts\c_mul_civ_club_short_dress2::main();
			break;
		case 2:
			character\clientscripts\c_mul_civ_club_short_dress3::main();
			break;
		case 3:
			character\clientscripts\c_mul_civ_club_short_dress4::main();
			break;
	}

	self._aitype = "Civilian_Club_Female_3";
}

precache(ai_index)
{
	character\clientscripts\c_mul_civ_club_short_dress1::precache();
	character\clientscripts\c_mul_civ_club_short_dress2::precache();
	character\clientscripts\c_mul_civ_club_short_dress3::precache();
	character\clientscripts\c_mul_civ_club_short_dress4::precache();

	UseFootstepTable(ai_index, "fly_step_civf");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
