// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_jinan_it_highres::main();
	self._aitype = "Civilian_IT_Manager_Karma";
}

precache(ai_index)
{
	character\clientscripts\c_mul_jinan_it_highres::precache();

	UseFootstepTable(ai_index, "fly_step_civm");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
