// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\C_mul_menendez_suit::main();
	self._aitype = "Hero_Menendez_Angola";
}

precache(ai_index)
{
	character\clientscripts\C_mul_menendez_suit::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
