// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_pan_noriega_casual_sack::main();
	self._aitype = "Hero_Noriega_Panama_Sack";
}

precache(ai_index)
{
	character\clientscripts\c_pan_noriega_casual_sack::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
