// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_farid_yemen::main();
	self._aitype = "Hero_Farid_Yemen";
}

precache(ai_index)
{
	character\clientscripts\c_mul_farid_yemen::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
