// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_rus_jungmar_pow_reznov::main();
	self._aitype = "Hero_Reznov_Afghan";
}

precache(ai_index)
{
	character\clientscripts\c_rus_jungmar_pow_reznov::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
