// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_menendez_suit_bleed::main();
	self._aitype = "Hero_Menendez_Blackout";
}

precache(ai_index)
{
	character\clientscripts\c_mul_menendez_suit_bleed::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
