// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_rus_afghan_kravchenko::main();
	self._aitype = "Hero_Kravcenko_Afghan";
}

precache(ai_index)
{
	character\clientscripts\c_rus_afghan_kravchenko::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
