// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_unioninsp_redshirt2::main();
	self._aitype = "Hero_Redshirt2_Karma";
}

precache(ai_index)
{
	character\clientscripts\c_usa_unioninsp_redshirt2::precache();

	UseFootstepTable(ai_index, "default_ai");
}

