// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_cc_briggs::main();
	self._aitype = "Hero_Briggs_Blackout";
}

precache(ai_index)
{
	character\clientscripts\c_usa_cc_briggs::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
