// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_tshirt_mason::main();
	self._aitype = "Mason_int_escape";
}

precache(ai_index)
{
	character\clientscripts\c_usa_tshirt_mason::precache();

	UseFootstepTable(ai_index, "default_ai");
}

