// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

#using_animtree("zm_transit_screecher");
main()
{
	character\clientscripts\c_zom_screecher::main();
	self._aitype = "zm_zombie_transit_screecher";
}

precache(ai_index)
{
	character\clientscripts\c_zom_screecher::precache();

	UseFootstepTable(ai_index, "default_ai");
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_screecher" );

	SetDemoLockOnValues( ai_index, 100, 18, 0, 60, 8, 0, 60 );
}
