// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

#using_animtree("zm_transit_avogadro");
main()
{
	character\clientscripts\c_zom_electrician::main();
	self._aitype = "zm_zombie_transit_avogadro";
}

precache(ai_index)
{
	character\clientscripts\c_zom_electrician::precache();

	UseFootstepTable(ai_index, "default_ai");
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_avogadro" );

	SetDemoLockOnValues( ai_index, 100, 70, -15, 60, 8, 0, 60 );
}
