// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

#using_animtree("zm_transit_dog");
main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\character_sp_zombie_dog::main();
			break;
		case 1:
			character\clientscripts\character_sp_zombie_dog::main();
			break;
	}

	self._aitype = "zombie_dog";
}

precache(ai_index)
{
	character\clientscripts\character_sp_zombie_dog::precache();
	character\clientscripts\character_sp_zombie_dog::precache();

	UseFootstepTable(ai_index, "default_ai");
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_dog" );

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
