// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_rich_male_blk_upper2_1";
	a[1] = "c_mul_civ_rich_male_blk_upper2_2";
	a[2] = "c_mul_civ_rich_male_blk_upper2_3";
	a[3] = "c_mul_civ_rich_male_blk_upper2_4";
	a[4] = "c_mul_civ_rich_male_blk_upper2_5";
	return a;
}
