// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_mul_civ_club_male_head1";
	a[1] = "c_mul_civ_club_male_head5";
	a[2] = "c_mul_civ_club_male_head7";
	a[3] = "c_mul_civ_club_male_head8";
	return a;
}
