// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "c_rus_prisoner_head1";
	a[1] = "c_rus_prisoner_head2";
	a[2] = "c_rus_prisoner_head3";
	a[3] = "c_rus_prisoner_head4";
	a[4] = "c_rus_prisoner_head5";
	return a;
}
