// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_rus_spetznaz_mp_lmg_fb");
	self setViewmodel("viewhands_usmc");
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_spetznaz_mp_lmg_fb");
	precacheModel("viewhands_usmc");
}
