// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_pent_nixon_fb_zt");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_pent_nixon_fb_zt");
}
