// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_specops_mp_smg_fb");
	self setViewmodel("viewhands_usmc");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_specops_mp_smg_fb");
	precacheModel("viewhands_usmc");
}
