// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_milcas_skinner_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_milcas_skinner_fb");
}
