// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_gov_body1");
	self.headModel = "c_usa_pent_officeworker_head3";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_gov_body1");
	precacheModel("c_usa_pent_officeworker_head3");
}
