// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_vtn_vc2_fb_drone");
	self.voice = "vietnamese";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_vtn_vc2_fb_drone");
}
