// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_opforce_afghan_lmg");
	codescripts\character::attachHead( "alias_opforce_afghan_heads", xmodelalias\alias_opforce_afghan_heads::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("body_opforce_afghan_lmg");
	codescripts\character::precacheModelArray(xmodelalias\alias_opforce_afghan_heads::main());
}
