// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_afr_mpla_body1");
	self.headModel = codescripts\character::randomElement(xmodelalias\c_afr_mpla_head_als::main());
	self attach(self.headModel, "", true);
	self.hatModel = codescripts\character::randomElement(xmodelalias\c_afr_mpla_headgear_als::main());
	self attach(self.hatModel, "", true);
	self.gearModel = codescripts\character::randomElement(xmodelalias\c_afr_mpla_body1_gear_als::main());
	self attach(self.gearModel, "", true);
	self.voice = "vietnamese";
	self.skeleton = "base";
	self.torsoDmg1 = "c_afr_mpla_body1_g_upclean";
	self.torsoDmg2 = "c_afr_mpla_body1_g_rarm";
	self.torsoDmg3 = "c_afr_mpla_body1_g_larm";
	self.torsoDmg4 = "c_afr_mpla_body1_g_barm";
	self.torsoDmg5 = "c_afr_mpla_body1_g_behead";
	self.legDmg1 = "c_afr_mpla_body1_g_lowclean";
	self.legDmg2 = "c_afr_mpla_body1_g_rleg";
	self.legDmg3 = "c_afr_mpla_body1_g_lleg";
	self.legDmg4 = "c_afr_mpla_body1_g_bleg";
	self.gibSpawn1 = "c_afr_mpla_spawn_rarm";
	self.gibSpawnTag1 = "J_Elbow_RI";
	self.gibSpawn2 = "c_afr_mpla_spawn_larm";
	self.gibSpawnTag2 = "J_Elbow_LE";
	self.gibSpawn3 = "c_afr_mpla_spawn_rleg";
	self.gibSpawnTag3 = "J_Knee_RI";
	self.gibSpawn4 = "c_afr_mpla_spawn_lleg";
	self.gibSpawnTag4 = "J_Knee_LE";
	self.gibSpawn5 = "c_afr_mpla_spawn_head";
	self.gibSpawnTag5 = "J_Neck";
}

precache()
{
	precacheModel("c_afr_mpla_body1");
	codescripts\character::precacheModelArray(xmodelalias\c_afr_mpla_head_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_afr_mpla_headgear_als::main());
	codescripts\character::precacheModelArray(xmodelalias\c_afr_mpla_body1_gear_als::main());
	precacheModel("c_afr_mpla_body1_g_upclean");
	precacheModel("c_afr_mpla_body1_g_rarm");
	precacheModel("c_afr_mpla_body1_g_larm");
	precacheModel("c_afr_mpla_body1_g_barm");
	precacheModel("c_afr_mpla_body1_g_behead");
	precacheModel("c_afr_mpla_body1_g_lowclean");
	precacheModel("c_afr_mpla_body1_g_rleg");
	precacheModel("c_afr_mpla_body1_g_lleg");
	precacheModel("c_afr_mpla_body1_g_bleg");
	precacheModel("c_afr_mpla_spawn_rarm");
	precacheModel("c_afr_mpla_spawn_larm");
	precacheModel("c_afr_mpla_spawn_rleg");
	precacheModel("c_afr_mpla_spawn_lleg");
	precacheModel("c_afr_mpla_spawn_head");
}
