// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_afg_mullah_omar_cin_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_afg_mullah_omar_cin_fb");
}
