// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_vtol_pilot_body");
	self.headModel = "c_mul_vtol_pilot_head2";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_vtol_pilot_body");
	precacheModel("c_mul_vtol_pilot_head2");
}
