// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_mul_pmc_assault_body_3");
	self.headModel = "c_mul_pmc_shotgun_head_2";
	self attach(self.headModel, "", true);
	self.hatModel = "c_mul_pmc_helmet_main";
	self attach(self.hatModel);
	self.gearModel = "c_mul_pmc_shotgun_gear_2";
	self attach(self.gearModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_mul_pmc_assault_body_3");
	precacheModel("c_mul_pmc_shotgun_head_2");
	precacheModel("c_mul_pmc_helmet_main");
	precacheModel("c_mul_pmc_shotgun_gear_2");
}
