// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_rus_afghan_kravchenko_fb");
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_rus_afghan_kravchenko_fb");
}
