// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_afr_mod10_easy_med_3_zt");
	self.voice = "russian";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_afr_mod10_easy_med_3_zt");
}
