// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_chloe_karma_body");
	self.headModel = "c_usa_chloe_head_cin";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_chloe_karma_body");
	precacheModel("c_usa_chloe_head_cin");
}
