// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_usa_seal6_assault_body");
	self.headModel = "c_usa_seal6_assault_head";
	self attach(self.headModel, "", true);
	self.hatModel = "c_usa_seal6_assault_gear";
	self attach(self.hatModel);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_usa_seal6_assault_body");
	precacheModel("c_usa_seal6_assault_head");
	precacheModel("c_usa_seal6_assault_gear");
}
