// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("c_yem_repguard_body");
	self.headModel = "c_yem_repguard_head1";
	self attach(self.headModel, "", true);
	self.gearModel = "c_yem_repguard_gear3";
	self attach(self.gearModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("c_yem_repguard_body");
	precacheModel("c_yem_repguard_head1");
	precacheModel("c_yem_repguard_gear3");
}
