// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/character_Foley");
	self attach("xmodel/head_Foley");
	self.hatModel = "xmodel/gear_US_helmet_scrim";
	self attach(self.hatModel);
	if (character\_utility::useOptionalModels())
	{
		self attach("xmodel/gear_US_Foley");
	}
	self.voice = "foley";
}

precache()
{
	precacheModel("xmodel/character_Foley");
	precacheModel("xmodel/head_Foley");
	precacheModel("xmodel/gear_US_helmet_scrim");
	if (character\_utility::useOptionalModels())
	{
		precacheModel("xmodel/gear_US_Foley");
	}
}
