// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_ally_so_riotshield (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_gign_paris_smg"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "allies";
	self.type = "human";
	self.subclass = "riotshield";
	self.accuracy = 0.2;
	self.health = 100;
	self.secondaryweapon = "iw5_riotshield_so";
	self.sidearm = "";
	self.grenadeWeapon = "";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 256.000000, 0.000000 );
		self setEngagementMaxDist( 768.000000, 1024.000000 );
	}

	self.weapon = "none";

	switch( codescripts\character::get_random_character(2) )
	{
	case 0:
		character\character_gign_paris_smg::main();
		break;
	case 1:
		character\character_gign_paris_assault::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\character_gign_paris_smg::precache();
	character\character_gign_paris_assault::precache();

	precacheItem("iw5_riotshield_so");

	//----------------
	maps\_riotshield::init_riotshield();
	//----------------
}
