// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_enemy_juggernaut_riotshield (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="fullbody_juggernaut_b"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "juggernaut_riotshield.csv";
	self.team = "axis";
	self.type = "human";
	self.subclass = "riotshield";
	self.accuracy = 0.2;
	self.health = 3600;
	self.secondaryweapon = "iw5_riotshield_so";
	self.sidearm = "fnfiveseven";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 0.000000, 0.000000 );
		self setEngagementMaxDist( 256.000000, 1024.000000 );
	}

	self.weapon = "pecheneg";

	character\character_so_juggernaut_mid::main();
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_so_juggernaut_mid::precache();

	precacheItem("pecheneg");
	precacheItem("iw5_riotshield_so");
	precacheItem("fnfiveseven");
	precacheItem("fraggrenade");

	//----------------
	maps\_riotshield::init_riotshield(); maps\_juggernaut::main(); 
	//----------------
}
