// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_jap_impinf_body4_cap1";
	a[1] = "char_jap_impinf_body4_helmc_less";
	a[2] = "char_jap_impinf_body4_helm2";
	a[3] = "char_jap_impinf_body4_hband";
	return a;
}
