// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "char_jap_impinf_body4_gear1";
	a[1] = "char_jap_impinf_body4_gear2";
	a[2] = "char_jap_impinf_body4_gear3";
	a[3] = "char_jap_impinf_body4_gear4";
	return a;
}
