// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_seal80s_heavy::main();
	self._aitype = "Ally_SEAL_Panama_Assault_covered";
}

precache(ai_index)
{
	character\clientscripts\c_usa_seal80s_heavy::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
