// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_lapd_medic::main();
	self._aitype = "Ally_LAPD_Medic_Base";
}

precache(ai_index)
{
	character\clientscripts\c_usa_lapd_medic::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
