// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_usa_jungmar_assault::main();
			break;
		case 1:
			character\clientscripts\c_usa_jungmar_cqb::main();
			break;
	}

	self._aitype = "Ally_SEAL_Yemen_SMG_Base";
}

precache(ai_index)
{
	character\clientscripts\c_usa_jungmar_assault::precache();
	character\clientscripts\c_usa_jungmar_cqb::precache();

	UseFootstepTable(ai_index, "default_ai");
}
