// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_mul_civ_generic_male_7::main();
			break;
		case 1:
			character\clientscripts\c_mul_civ_generic_male_8::main();
			break;
	}

	self._aitype = "Civilian_Rich_Male_4";
}

precache(ai_index)
{
	character\clientscripts\c_mul_civ_generic_male_7::precache();
	character\clientscripts\c_mul_civ_generic_male_8::precache();

	UseFootstepTable(ai_index, "fly_step_civm");
}
