// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_redcross_nurse::main();
	self._aitype = "Civilian_Panama_Nurse";
}

precache(ai_index)
{
	character\clientscripts\c_mul_redcross_nurse::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
