// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_civ_rich_female_2::main();
	self._aitype = "Civilian_Rich_Female_2";
}

precache(ai_index)
{
	character\clientscripts\c_mul_civ_rich_female_2::precache();

	UseFootstepTable(ai_index, "fly_step_civf");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
