// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_mul_civ_rich_male_1::main();
			break;
		case 1:
			character\clientscripts\c_mul_civ_rich_male_1_2::main();
			break;
		case 2:
			character\clientscripts\c_mul_civ_rich_male_2::main();
			break;
		case 3:
			character\clientscripts\c_mul_civ_rich_male_2_2::main();
			break;
		case 4:
			character\clientscripts\c_mul_civ_rich_male_3::main();
			break;
		case 5:
			character\clientscripts\c_mul_civ_rich_male_3_2::main();
			break;
	}

	self._aitype = "Civilian_Rich_Male";
}

precache(ai_index)
{
	character\clientscripts\c_mul_civ_rich_male_1::precache();
	character\clientscripts\c_mul_civ_rich_male_1_2::precache();
	character\clientscripts\c_mul_civ_rich_male_2::precache();
	character\clientscripts\c_mul_civ_rich_male_2_2::precache();
	character\clientscripts\c_mul_civ_rich_male_3::precache();
	character\clientscripts\c_mul_civ_rich_male_3_2::precache();

	UseFootstepTable(ai_index, "fly_step_civm");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
