// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_vtol_pilot2::main();
	self._aitype = "Civilian_Pilot_2";
}

precache(ai_index)
{
	character\clientscripts\c_mul_vtol_pilot2::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
