// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_jinan_demoworker_bscatter_off::main();
	self._aitype = "Civilian_Worker_Construction";
}

precache(ai_index)
{
	character\clientscripts\c_mul_jinan_demoworker_bscatter_off::precache();

	UseFootstepTable(ai_index, "fly_step_civm");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
