// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_vtn_civ_macv::main();
	self._aitype = "Civilian_Panama_Male";
}

precache(ai_index)
{
	character\clientscripts\c_vtn_civ_macv::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
