// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\character_mp_german_shepherd::main();
	self._aitype = "enemy_dog_mp";
}

precache(ai_index)
{
	character\clientscripts\character_mp_german_shepherd::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
