// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_rus_spetznaz_1::main();
	self._aitype = "Enemy_LeT_Pakistan_Shotgun_Base";
}

precache(ai_index)
{
	character\clientscripts\c_rus_spetznaz_1::precache();

	UseFootstepTable(ai_index, "default_ai");
}
