// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_t6_claw_mk2::main();
	self._aitype = "Enemy_BigDog";
}

precache(ai_index)
{
	character\clientscripts\c_t6_claw_mk2::precache();

	UseFootstepTable(ai_index, "default_ai");
	ScriptCallbackOnFootstepEvent(ai_index);

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
