// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_defalco_karma_cin::main();
	self._aitype = "Hero_Defalco_Pakistan";
}

precache(ai_index)
{
	character\clientscripts\c_mul_defalco_karma_cin::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
