// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_chloe_lynch_organs::main();
	self._aitype = "Hero_Karma_Karma_Scan";
}

precache(ai_index)
{
	character\clientscripts\c_usa_chloe_lynch_organs::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
