// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_gov_presstaff1::main();
	self._aitype = "Hero_Johnson_LA";
}

precache(ai_index)
{
	character\clientscripts\c_usa_gov_presstaff1::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
