// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_usa_interrogation_sillhouette::main();
	self._aitype = "Hudson_int_silhoutte";
}

precache(ai_index)
{
	character\clientscripts\c_usa_interrogation_sillhouette::precache();

	UseFootstepTable(ai_index, "default_ai");
}

