// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_usa_secserv_light::main();
			break;
		case 1:
			character\clientscripts\c_usa_secserv_medium::main();
			break;
	}

	self._aitype = "So_Ally_Assault_Base";
}

precache(ai_index)
{
	character\clientscripts\c_usa_secserv_light::precache();
	character\clientscripts\c_usa_secserv_medium::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
