// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	switch(self GetCharacterIndex())
	{
		case 0:
			character\clientscripts\c_mul_pmc_shotgun::main();
			break;
		case 1:
			character\clientscripts\c_mul_pmc_shotgun_2::main();
			break;
		case 2:
			character\clientscripts\c_mul_pmc_shotgun_3::main();
			break;
	}

	self._aitype = "So_Enemy_Shotgun_Base";
}

precache(ai_index)
{
	character\clientscripts\c_mul_pmc_shotgun::precache();
	character\clientscripts\c_mul_pmc_shotgun_2::precache();
	character\clientscripts\c_mul_pmc_shotgun_3::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
