// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

main()
{
	character\clientscripts\c_mul_pmc_shotgun::main();
	self._aitype = "So_Enemy_Juggernaut_Assault_Base";
}

precache(ai_index)
{
	character\clientscripts\c_mul_pmc_shotgun::precache();

	UseFootstepTable(ai_index, "default_ai");

	SetDemoLockOnValues( ai_index, 100, 8, 0, 60, 8, 0, 60 );
}
