// THIS FILE IS AUTOGENERATED, DO NOT MODIFY

#using_animtree("zm_transit_basic");
main()
{
	character\clientscripts\c_zom_cosmo_spetznaz::main();
	self._aitype = "zm_zombie_cosmo_spetznaz";
}

precache(ai_index)
{
	character\clientscripts\c_zom_cosmo_spetznaz::precache();

	UseFootstepTable(ai_index, "default_ai");
	PrecacheAnimStateDef( ai_index, #animtree, "zm_transit_basic" );

	SetDemoLockOnValues( ai_index, 100, 60, -15, 60, 30, -5, 60 );
}
