
;========== TELEPORT SCRIPTS ==========

(script static void tele_vehicle_int
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 1)
	(print "teleporting players...")
	(object_teleport (player0) vehicle_int_a)
	(object_teleport (player1) vehicle_int_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake enc_vehicle_int)
	(sleep 10)
	(player_enable_input true)
		
	(sleep_until (volume_test_objects tv_qz_ext_a (players)))
	(wake enc_qz_ext_a)
	
	(sleep_until (volume_test_objects tv_factory (players)))
	(wake enc_crashed_factory)

	(sleep_until (volume_test_objects tv_qz_ext_b (players)))
	(wake enc_qz_ext_b)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)
	
	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)

)

(script static void tele_ext_a
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 1)
	(print "teleporting players...")
	(object_teleport (player0) qz_ext_a_a)
	(object_teleport (player1) qz_ext_a_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake enc_qz_ext_a)
	(sleep 10)
	(player_enable_input true)
		
	(sleep_until (volume_test_objects tv_factory (players)))
	(wake enc_crashed_factory)

	(sleep_until (volume_test_objects tv_qz_ext_b (players)))
	(wake enc_qz_ext_b)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)
	
	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)

)

(script static void tele_factory_1
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 2)
	(print "teleporting players...")
	(object_teleport (player0) factory1_a)
	(object_teleport (player1) factory1_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake enc_crashed_factory)
	(sleep 10)
	(player_enable_input true)
		
	(sleep_until (volume_test_objects tv_qz_ext_b (players)))
	(wake enc_qz_ext_b)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)
	
	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)
)

;*
(script static void tele_factory_gorge
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 2)
	(print "teleporting players...")
	(object_teleport (player0) gorge_a)
	(object_teleport (player1) gorge_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")

;	(wake factory_gorge_start)
	(sleep 10)
	(player_enable_input true)

	(sleep_until (= (volume_test_objects vol_factory_2_enter (players)) TRUE)) 
	(wake sent_factory_2_start)
		
	(sleep_until (volume_test_objects tv_qz_ext_b (players)))
	(wake enc_qz_ext_b)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)
	
	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)

)

(script static void tele_factory_2
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 2)
	(print "teleporting players...")
	(object_teleport (player0) factory2_a)
	(object_teleport (player1) factory2_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake sent_factory_2_start)
	(sleep 10)
	(player_enable_input true)
		
	(sleep_until (volume_test_objects tv_qz_ext_b (players)))
	(wake enc_qz_ext_b)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)

	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)

)
*;

(script static void tele_ext_b
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 2)
	(print "teleporting players...")
	(object_teleport (player0) qz_ext_b_a)
	(object_teleport (player1) qz_ext_b_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake enc_qz_ext_b)
	(sleep 10)
	(player_enable_input true)

	(sleep_until (volume_test_objects tv_key_ride (players)))
	(wake enc_key_ride)

	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)
)

(script static void tele_key
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 3)
	(print "teleporting players...")
	(object_teleport (player0) key_ride_a)
	(object_teleport (player1) key_ride_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(wake enc_key_ride)
	(sleep 10)
	(player_enable_input true)

	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)
)

(script static void tele_library
	(fade_out 0 0 0 0)
	(sleep 1)
	(player_enable_input false)
	(print "switching bsp...")
	(sleep 15)
	(switch_bsp 4)
	(print "teleporting players...")
	(object_teleport (player0) library_a)
	(object_teleport (player1) library_b)
	(fade_in 0 0 0 60)
	(print "erasing ai...")
	(ai_erase_all)
	(sleep 5)
	(print "initializing area scripts...")
	(sleep 10)
	(player_enable_input true)

	(sleep_until (volume_test_objects tv_x07 (players)))
	(if (cinematic_skip_start)
		(begin
			(print "x07")
			(x07)			
		)
	)
	(cinematic_skip_stop)
	(game_won)
)
