#define SCORE_EVENT_TABLE_NAME "mp/scoreInfo.csv"

#define SCORE_EVENT_SCRIPT_REFERENCE 			0
#define SCORE_EVENT_SCORE_STRING 				1
#define SCORE_EVENT_MEDAL_REFERENCE				2
#define SCORE_EVENT_MEDAL_MATERIAL				3
#define SCORE_EVENT_ALLOW_KILLSTREAK_WEAPONS	4
#define SCORE_EVENT_SET_STATS					5
#define SCORE_EVENT_DOUBLE_XP 					6
#define SCORE_EVENT_GAMETYPE_SCORE 				7
#define SCORE_EVENT_GAMETYPE_XP 				8

#define SCORE_EVENT_GAMETYPE_COLUMN_SCORE 	0
#define SCORE_EVENT_GAMETYPE_COLUMN_XP		1
#define SCORE_EVENT_GAMETYPE_COLUMN_COUNT 	2

#define SCORE_EVENT_MAX_COUNT 	1024

#define SCORE_EVENT_MEDAL_WAIT_TIME 2

#define SCORE_EVENT_OBITUARY_CENTERTIME 5