// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("char_usa_pbycrew_body1_2");
	self.headModel = "char_usa_marine_head2_2";
	self attach(self.headModel, "", true);
	self.hatModel = "char_usa_pbycrew_cap";
	self attach(self.hatModel);
	self.voice = "american";
}

precache()
{
	precacheModel("char_usa_pbycrew_body1_2");
	precacheModel("char_usa_marine_head2_2");
	precacheModel("char_usa_pbycrew_cap");
}
