-- Copyright (c) Microsoft. All rights reserved.

-- THIS CODE IS GENERATED BY THE VISUAL ANIMATION GRAPH EDITOR -- 

-- GENERATED LUA DECLARATIONS --



-- GENERATED LUA CODE --

function replacement_put_away()

	local AnimationWithGroupName_BDFFJAJIIJHDFGDFGD:table = AnimGraph.CreateAnimationWithGroupName("put_away", false, 1.000000, "put_away", 1.000000);

	return AnimationWithGroupName_BDFFJAJIIJHDFGDFGD;
end

function replacement_ready()

	local AnimationWithGroupName_BDFFJAJIIJHDFGDFGD:table = AnimGraph.CreateAnimationWithGroupName("ready", false, 1.000000, "ready", 1.000000);

	return AnimationWithGroupName_BDFFJAJIIJHDFGDFGD;
end

