-- Copyright (c) Microsoft. All rights reserved.

-- THIS CODE IS GENERATED BY THE VISUAL ANIMATION GRAPH EDITOR -- 

-- GENERATED LUA DECLARATIONS --



-- GENERATED LUA CODE --

function isInLocomotion()
	
	local LOGIC_AND:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);

	local LOGIC_GREATERTHAN:table = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan);

	local float_const_zero:table = AnimGraph.CreateConstantFloat(0.0);

	local linear_movement_speed:table = AnimGraph.CreateFloatControlParameter("linear_movement_speed");

	local ground:table = AnimGraph.CreateBoolControlParameter("ground");
	
	NG.CreateLink(linear_movement_speed.Out, LOGIC_GREATERTHAN.Left);
	NG.CreateLink(float_const_zero.Out, LOGIC_GREATERTHAN.Right);

	NG.CreateLink(LOGIC_GREATERTHAN.Out, LOGIC_AND.MultiIn);
	NG.CreateLink(ground.Out, LOGIC_AND.MultiIn);

	return LOGIC_AND;
end

function isInIdle()

	local LOGIC_AND:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);

	local LOGIC_EQUAL:table = AnimGraph.CreateNumericalLogic(NG.NumCond.Equal);

	local float_const_zero:table = AnimGraph.CreateConstantFloat(0.0);

	local linear_movement_speed:table = AnimGraph.CreateFloatControlParameter("linear_movement_speed");

	local ground:table = AnimGraph.CreateBoolControlParameter("ground");
	
	NG.CreateLink(linear_movement_speed.Out, LOGIC_EQUAL.Left);
	NG.CreateLink(float_const_zero.Out, LOGIC_EQUAL.Right);

	NG.CreateLink(LOGIC_EQUAL.Out, LOGIC_AND.MultiIn);
	NG.CreateLink(ground.Out, LOGIC_AND.MultiIn);

	return LOGIC_AND;
end

function isFiring()

	local ReturnBool_BHGFJAEBEGDCHGDD:table = nil;
	local NumericalLogic_CJAJHAEBEGDCHGDD:table = AnimGraph.CreateNumericalLogic(NG.NumCond.Equal);
	local ObjectFunction_AAGIIAEBEGDCHGDD:table = AnimGraph.CreateObjectFunction("primary_firing");
	local Float_BHAAHAEBEGDCHGD:table = AnimGraph.CreateConstantFloat(1.000000);

	
	NG.CreateLink(ObjectFunction_AAGIIAEBEGDCHGDD.Out, NumericalLogic_CJAJHAEBEGDCHGDD.Left);
	NG.CreateLink(Float_BHAAHAEBEGDCHGD.Out, NumericalLogic_CJAJHAEBEGDCHGDD.Right);
	

	return NumericalLogic_CJAJHAEBEGDCHGDD;
end

function is_in_stationary_turn_left()

	local ReturnBool_JHCJCCEBEGDCHGDD:table = nil;
	local NumericalLogic_BAABJBEBEGDCHGDD:table = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan);
	local FunctionNode_AHHJBCEBEGDCHGDD:table = control_stationary_turn_rate()
	local Float_GICJACEBEGDCHGD:table = AnimGraph.CreateConstantFloat(0.010000);

	
	NG.CreateLink(FunctionNode_AHHJBCEBEGDCHGDD.Out, NumericalLogic_BAABJBEBEGDCHGDD.Left);
	NG.CreateLink(Float_GICJACEBEGDCHGD.Out, NumericalLogic_BAABJBEBEGDCHGDD.Right);
	

	return NumericalLogic_BAABJBEBEGDCHGDD;
end

function is_in_stationary_turn_right()

	local ReturnBool_GFAIDCEBEGDCHGDD:table = nil;
	local NumericalLogic_CCAAACEBEGDCHGDD:table = AnimGraph.CreateNumericalLogic(NG.NumCond.LessThan);
	local FunctionNode_AHHJBCEBEGDCHGDD:table = control_stationary_turn_rate()
	local Float_BBBFICEBEGDCHGD:table = AnimGraph.CreateConstantFloat(-0.010000);

	
	NG.CreateLink(FunctionNode_AHHJBCEBEGDCHGDD.Out, NumericalLogic_CCAAACEBEGDCHGDD.Left);
	NG.CreateLink(Float_BBBFICEBEGDCHGD.Out, NumericalLogic_CCAAACEBEGDCHGDD.Right);
	

	return NumericalLogic_CCAAACEBEGDCHGDD;
end

function isNOT_in_stationary_turn()

	local ReturnBool_DJBCGCEBEGDCHGDD:table = nil;
	local BooleanInvert_ABGFFCEBEGDCHGDD:table = AnimGraph.CreateBooleanInvert();
	local BooleanLogic_JIFGECEBEGDCHGDD:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.OR);
	local NumericalLogic_BAABJBEBEGDCHGDD:table = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan);
	local FunctionNode_AHHJBCEBEGDCHGDD:table = control_stationary_turn_rate()
	local Float_GICJACEBEGDCHGD:table = AnimGraph.CreateConstantFloat(0.010000);
	local NumericalLogic_CCAAACEBEGDCHGDD:table = AnimGraph.CreateNumericalLogic(NG.NumCond.LessThan);
	local FunctionNode_AHHJBCEBEGDCHGDD:table = control_stationary_turn_rate()
	local Float_BBBFICEBEGDCHGD:table = AnimGraph.CreateConstantFloat(-0.010000);

	
	NG.CreateLink(BooleanLogic_JIFGECEBEGDCHGDD.Out, BooleanInvert_ABGFFCEBEGDCHGDD.In);
	NG.CreateLink(NumericalLogic_BAABJBEBEGDCHGDD.Out, BooleanLogic_JIFGECEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_AHHJBCEBEGDCHGDD.Out, NumericalLogic_BAABJBEBEGDCHGDD.Left);
	NG.CreateLink(Float_GICJACEBEGDCHGD.Out, NumericalLogic_BAABJBEBEGDCHGDD.Right);
	NG.CreateLink(NumericalLogic_CCAAACEBEGDCHGDD.Out, BooleanLogic_JIFGECEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_AHHJBCEBEGDCHGDD.Out, NumericalLogic_CCAAACEBEGDCHGDD.Left);
	NG.CreateLink(Float_BBBFICEBEGDCHGD.Out, NumericalLogic_CCAAACEBEGDCHGDD.Right);
	

	return BooleanInvert_ABGFFCEBEGDCHGDD;
end

function hasEndedLand_Soft()

	local ReturnBool_EFAHADEBEGDCHGDD:table = nil;
	local EndofAnimationDetection_BFDFJCEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimationWithGroupName(0.010000, "land_soft");

	
	

	return EndofAnimationDetection_BFDFJCEBEGDCHGDHGD;
end

function hasEndedAirborne()

	local ReturnBool_HIFFBDEBEGDCHGDD:table = nil;
	local boolparameter_BCBECDEBEGDCHGDD:table = AnimGraph.CreateBoolControlParameter("ground");

	
	

	return boolparameter_BCBECDEBEGDCHGDD;
end

function hasEndedFire()

	local ReturnBool_BFFGEDEBEGDCHGDD:table = nil;
	local EndofAnimationDetection_DCJBDDEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimationWithGroupName(0.000000,'fire');

	
	

	return EndofAnimationDetection_DCJBDDEBEGDCHGDHGD;
end


function hasEndedDead()

	local ReturnBool_FHICJDEBEGDCHGDD:table = nil;
	local EndofAnimationDetection_AJEIHDEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimation(0.100000);

	
	

	return EndofAnimationDetection_AJEIHDEBEGDCHGDHGD;
end

function isInAirborneDead()

	local ReturnBool_EIDCAEEBEGDCHGDD:table = nil;
	local BooleanLogic_DFBBDEEBEGDCHGDD:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	local FunctionNode_HBJABEEBEGDCHGDD:table = control_airborne()
	local FunctionNode_JIIBCEEBEGDCHGDD:table = control_dead()

	
	NG.CreateLink(FunctionNode_HBJABEEBEGDCHGDD.Out, BooleanLogic_DFBBDEEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_JIIBCEEBEGDCHGDD.Out, BooleanLogic_DFBBDEEBEGDCHGDD.MultiIn);
	

	return BooleanLogic_DFBBDEEBEGDCHGDD;
end

function isInLandingDead()

	local ReturnBool_EFGAGEEBEGDCHGDD:table = nil;
	local BooleanLogic_FCBCEEEBEGDCHGDD:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	local FunctionNode_JIIBCEEBEGDCHGDD:table = control_dead()
	local FunctionNode_AJDBFEEBEGDCHGDD:table = control_ground()

	NG.CreateLink(FunctionNode_JIIBCEEBEGDCHGDD.Out, BooleanLogic_FCBCEEEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_AJDBFEEBEGDCHGDD.Out, BooleanLogic_FCBCEEEBEGDCHGDD.MultiIn);

	return BooleanLogic_FCBCEEEBEGDCHGDD;
end

function hasEndedFullBodyState()

	local ReturnBool_BCHHHEEBEGDCHGDD:table = nil;

	local BooleanLogic_AAFFEFEBEGDCHGDD:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.OR);

	local EndofAnimationDetection_FCJIBFEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimation(0.000000);
	local EndofAnimationDetection_HJHDDFEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimation(0.000000);
	local EndofAnimationDetection_ping:table = AnimGraph.CreateEndOfAnimation(0.000000);
	local EndofAnimationDetection_custom_anim:table = AnimGraph.CreateEndOfAnimation(0.000000);
	local EndOfAnimationDetection_hard_stop:table = AnimGraph.CreateEndOfAnimation(0.000000);

	local CustomAnimationHasStartedCP = control_custom_animation_start();
	local CustomAnimationHasEndedCP = AnimGraph.CreateBooleanInvert();
	NG.CreateLink(CustomAnimationHasStartedCP.Out, CustomAnimationHasEndedCP.In);

	local isFullBodyPing = is_full_body_ping();
	local isEvade:table = control_dive()
	local isDive:table = control_evade()
	local isHardStop:table = AnimGraph.CreateBoolControlParameter("hard_stop");
	local isNotFullBodyPing = AnimGraph.CreateBooleanInvert();
	local isNotEvade = AnimGraph.CreateBooleanInvert();
	local isNotDive = AnimGraph.CreateBooleanInvert();
	local isNotHardStop = AnimGraph.CreateBooleanInvert();
	NG.CreateLink(isFullBodyPing.Out, isNotFullBodyPing.In);
	NG.CreateLink(isEvade.Out, isNotEvade.In);
	NG.CreateLink(isDive.Out, isNotDive.In);
	NG.CreateLink(isHardStop.Out, isNotHardStop.In);

	local isCustomAnimAndCustomAnimHasEnded:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	NG.CreateLink(CustomAnimationHasEndedCP.Out, isCustomAnimAndCustomAnimHasEnded.MultiIn);
	NG.CreateLink(isNotFullBodyPing.Out, isCustomAnimAndCustomAnimHasEnded.MultiIn);
	NG.CreateLink(isNotEvade.Out, isCustomAnimAndCustomAnimHasEnded.MultiIn);
	NG.CreateLink(isNotDive.Out, isCustomAnimAndCustomAnimHasEnded.MultiIn);
	NG.CreateLink(isNotHardStop.Out, isCustomAnimAndCustomAnimHasEnded.MultiIn);

	NG.CreateLink(EndofAnimationDetection_FCJIBFEBEGDCHGDHGD.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);
	NG.CreateLink(EndofAnimationDetection_HJHDDFEBEGDCHGDHGD.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);
	NG.CreateLink(EndofAnimationDetection_custom_anim.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);
	NG.CreateLink(EndofAnimationDetection_ping.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);
	NG.CreateLink(EndOfAnimationDetection_hard_stop.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);
	NG.CreateLink(isCustomAnimAndCustomAnimHasEnded.Out, BooleanLogic_AAFFEFEBEGDCHGDD.MultiIn);

	local isDead:table = AnimGraph.CreateBoolControlParameter("dead");
	local isNotDead:table = AnimGraph.CreateBooleanInvert();
	NG.CreateLink(isDead.Out, isNotDead.In);

	local fullBodyHasEndedAndIsNotDead:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	NG.CreateLink(isNotDead.Out, fullBodyHasEndedAndIsNotDead.MultiIn);
	NG.CreateLink(BooleanLogic_AAFFEFEBEGDCHGDD.Out, fullBodyHasEndedAndIsNotDead.MultiIn);

	return fullBodyHasEndedAndIsNotDead;
end

function fullBodyStateRequest()

	local ReturnBool_CEDCBFEBEGDCHGDD:table = nil;
	local BooleanLogic_AFHEJFEBEGDCHGDD:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.OR);

	local FunctionNode_ADAEGFEBEGDCHGDD:table = control_dive()
	local FunctionNode_GCAEHFEBEGDCHGDD:table = control_evade()
	local FunctionNode_control_custom_animation_start:table = control_custom_animation_start()
	local hardStopFunctionNode:table = AnimGraph.CreateBoolControlParameter("hard_stop")
	local isFullBodyPing = is_full_body_ping();

	NG.CreateLink(FunctionNode_ADAEGFEBEGDCHGDD.Out, BooleanLogic_AFHEJFEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_GCAEHFEBEGDCHGDD.Out, BooleanLogic_AFHEJFEBEGDCHGDD.MultiIn);
	NG.CreateLink(FunctionNode_control_custom_animation_start.Out, BooleanLogic_AFHEJFEBEGDCHGDD.MultiIn);
	NG.CreateLink(hardStopFunctionNode.Out, BooleanLogic_AFHEJFEBEGDCHGDD.MultiIn)
	NG.CreateLink(isFullBodyPing.Out, BooleanLogic_AFHEJFEBEGDCHGDD.MultiIn);

	return BooleanLogic_AFHEJFEBEGDCHGDD;
end

function hasEndedReplacement_ready()

	local ReturnBool_FHICJDEBEGDCHGDD:table = nil;
	local EndofAnimationDetection_AJEIHDEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimationWithGroupName(0.0, "ready")

	
	

	return EndofAnimationDetection_AJEIHDEBEGDCHGDHGD;
end

function hasEndedReplacement_put_away()

	local ReturnBool_FHICJDEBEGDCHGDD:table = nil;
	local EndofAnimationDetection_AJEIHDEBEGDCHGDHGD:table = AnimGraph.CreateEndOfAnimationWithGroupName(0.0, "put_away")

	
	

	return EndofAnimationDetection_AJEIHDEBEGDCHGDHGD;
end

	function isNOT_brace()
	local brace = AnimGraph.CreateBoolControlParameter("brace");
	local invert = AnimGraph.CreateBooleanInvert();

	NG.CreateLink(brace.Out, invert.In);

	return invert;
end

function hasEndedHunkerEnter()
	local end_of_animation:table = AnimGraph.CreateEndOfAnimation(0.05);	
	local boolean_logic:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	local brace = AnimGraph.CreateBoolControlParameter('brace')

	NG.CreateLink(end_of_animation.Out, boolean_logic.MultiIn);
	NG.CreateLink(brace.Out, boolean_logic.MultiIn);

	return boolean_logic;
end

function hasEndedHunkerExit()
	local end_of_animation:table = AnimGraph.CreateEndOfAnimation(0.0);	
	local boolean_logic:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);
	local brace = isNOT_brace()

	NG.CreateLink(end_of_animation.Out, boolean_logic.MultiIn);
	NG.CreateLink(brace.Out, boolean_logic.MultiIn);

	return boolean_logic;
end

function canPrefireEnter()
	local preparing_to_fire = preparingToFire();
	local grounded = AnimGraph.CreateBoolControlParameter("ground");
	local andBooleanLogic = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);	

	NG.CreateLink(grounded.Out, andBooleanLogic.MultiIn);
	NG.CreateLink(preparing_to_fire.Out, andBooleanLogic.MultiIn);

	return andBooleanLogic;
end

function isPrefireOrIsFiring()
	local prefire = AnimGraph.CreateObjectFunction('is_preparing_to_or_is_Firing')
	local num = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan)
	local zero = AnimGraph.CreateConstantFloat(0.0)

	NG.CreateLink(prefire.Out, num.Left);
	NG.CreateLink(zero.Out, num.Right);

	return num;
end

function isNotPrefireOrIsFiring()
	local prefiring = AnimGraph.CreateObjectFunction('is_preparing_to_or_is_Firing')
	local num = AnimGraph.CreateNumericalLogic(NG.NumCond.LessThan)
	local one = AnimGraph.CreateConstantFloat(1.0)

	NG.CreateLink(prefiring.Out, num.Left);
	NG.CreateLink(one.Out, num.Right);

	return num;
end

function preparingToFire()
	local prefire = AnimGraph.CreateObjectFunction('preparing_to_fire')
	local num = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan)
	local zero = AnimGraph.CreateConstantFloat(0.0)

	NG.CreateLink(prefire.Out, num.Left);
	NG.CreateLink(zero.Out, num.Right);

	return num;
end


function isPrefire()
	local prefire = AnimGraph.CreateObjectFunction('prefire')
	local num = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan)
	local zero = AnimGraph.CreateConstantFloat(0.0)

	NG.CreateLink(prefire.Out, num.Left);
	NG.CreateLink(zero.Out, num.Right);

	return num;
end

function hasEndedAnimation()
	local end_of_animation:table = AnimGraph.CreateEndOfAnimation(0.1);	
	return end_of_animation
end

function isNOT_prefire()
	local prefire = isPrefire()
	local invert = AnimGraph.CreateBooleanInvert();

	NG.CreateLink(prefire.Out, invert.In);

	return invert;
end

function isNOT_vehicle()
	local vehicle = is_vehicle()
	local invert = AnimGraph.CreateBooleanInvert();

	NG.CreateLink(vehicle.Out, invert.In);

	return invert;
end


function is_exiting_vehicle()
	local vehicle = isNOT_vehicle()
	local boolean_logic = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);	
	local end_of_animation:table = AnimGraph.CreateEndOfAnimation(0.05);

	NG.CreateLink(vehicle.Out, boolean_logic.MultiIn);
	NG.CreateLink(end_of_animation.Out, boolean_logic.MultiIn);

	return boolean_logic;
end

function is_vehicle()
	local vehicle_enter = AnimGraph.CreateBoolControlParameter('vehicle_enter')
	local vehicle = AnimGraph.CreateBoolControlParameter('vehicle')
	-- local vehicle_exit = AnimGraph.CreateBoolControlParameter('vehicle_exit')
	local vehicle_melee = AnimGraph.CreateBoolControlParameter('vehicle_melee')
	local vehicle_boarding = AnimGraph.CreateBoolControlParameter('vehicle_board')
	local vehicle_eject = AnimGraph.CreateBoolControlParameter('vehicle_eject')

	local boolean_logic = AnimGraph.CreateBooleanLogic(NG.BoolOp.OR);	

	NG.CreateLink(vehicle_enter.Out, boolean_logic.MultiIn);
	NG.CreateLink(vehicle.Out, boolean_logic.MultiIn);
	-- NG.CreateLink(vehicle_exit.Out, boolean_logic.MultiIn);
	NG.CreateLink(vehicle_melee.Out, boolean_logic.MultiIn);
	NG.CreateLink(vehicle_boarding.Out, boolean_logic.MultiIn);
	NG.CreateLink(vehicle_eject.Out, boolean_logic.MultiIn);
	
	return boolean_logic;
end

function player_isInLocomotion()

	local LOGIC_AND:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);

	local LOGIC_GREATERTHAN_:table = AnimGraph.CreateNumericalLogic(NG.NumCond.GreaterThan);

	local float_const:table = AnimGraph.CreateConstantFloat(0.01);

	local animation_throttle_magnitude:table = AnimGraph.CreateObjectFunction("animation_throttle_magnitude");

	local ground:table = AnimGraph.CreateBoolControlParameter("ground");

	NG.CreateLink(animation_throttle_magnitude.Out, LOGIC_GREATERTHAN_.Left);
	NG.CreateLink(float_const.Out, LOGIC_GREATERTHAN_.Right);

	NG.CreateLink(ground.Out, LOGIC_AND.MultiIn);
	NG.CreateLink(LOGIC_GREATERTHAN_.Out, LOGIC_AND.MultiIn);

	return LOGIC_AND;
end

function player_isInIdle()

	local LOGIC_AND:table = AnimGraph.CreateBooleanLogic(NG.BoolOp.AND);

	local LOGIC_LESSTHAN_:table = AnimGraph.CreateNumericalLogic(NG.NumCond.LessThanEq);

	local float_const:table = AnimGraph.CreateConstantFloat(0.01);

	local animation_throttle_magnitude:table = AnimGraph.CreateObjectFunction("animation_throttle_magnitude");

	local ground:table = AnimGraph.CreateBoolControlParameter("ground");

	NG.CreateLink(animation_throttle_magnitude.Out, LOGIC_LESSTHAN_.Left);
	NG.CreateLink(float_const.Out, LOGIC_LESSTHAN_.Right);

	NG.CreateLink(ground.Out, LOGIC_AND.MultiIn);
	NG.CreateLink(LOGIC_LESSTHAN_.Out, LOGIC_AND.MultiIn);

	return LOGIC_AND;
end