// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_ally_airborne_thompson (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE NOENEMYINFO
defaultmdl="xmodel/Airborne"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
NOENEMYINFO -- this AI when spawned will not get a snapshot of perfect info about all enemies
*/
main()
{
	self.team = "allies";
	self.accuracy = 0.4;
	self.health = 350;
	self.weapon = "thompson";
	self.secondaryweapon = "";
	self.grenadeWeapon = "fraggrenade";
	self.scariness = 1;
	self.bravery = 6;
	self.grenadeAmmo = 0;

	switch(randomint(12))
	{
	case 0:
		character\Airborne1a_thompson::main();
		break;
	case 1:
		character\Airborne1b_thompson::main();
		break;
	case 2:
		character\Airborne1c_thompson::main();
		break;
	case 3:
		character\Airborne1d_thompson::main();
		break;
	case 4:
		character\Airborne2a_thompson::main();
		break;
	case 5:
		character\Airborne2b_thompson::main();
		break;
	case 6:
		character\Airborne2c_thompson::main();
		break;
	case 7:
		character\Airborne2d_thompson::main();
		break;
	case 8:
		character\Airborne3a_thompson::main();
		break;
	case 9:
		character\Airborne3b_thompson::main();
		break;
	case 10:
		character\Airborne3c_thompson::main();
		break;
	case 11:
		character\Airborne3d_thompson::main();
		break;
	}
}

precache()
{
	character\Airborne1a_thompson::precache();
	character\Airborne1b_thompson::precache();
	character\Airborne1c_thompson::precache();
	character\Airborne1d_thompson::precache();
	character\Airborne2a_thompson::precache();
	character\Airborne2b_thompson::precache();
	character\Airborne2c_thompson::precache();
	character\Airborne2d_thompson::precache();
	character\Airborne3a_thompson::precache();
	character\Airborne3b_thompson::precache();
	character\Airborne3c_thompson::precache();
	character\Airborne3d_thompson::precache();

	precacheItem("thompson");
	precacheItem("fraggrenade");
}
