// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_axis_wehrmacht_soldier_kar98k (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE NOENEMYINFO
defaultmdl="xmodel/character_german_WehrmactB"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
NOENEMYINFO -- this AI when spawned will not get a snapshot of perfect info about all enemies
*/
main()
{
	self.team = "axis";
	self.accuracy = 0.4;
	self.health = 100;
	self.weapon = "kar98k";
	self.secondaryweapon = "";
	self.grenadeWeapon = "Stielhandgranate";
	self.scariness = 1;
	self.bravery = 50;
	self.grenadeAmmo = 0;

	switch(randomint(5))
	{
	case 0:
		character\wehrmacht_soldier_K98a::main();
		break;
	case 1:
		character\wehrmacht_soldier_K98b::main();
		break;
	case 2:
		character\wehrmacht_soldier_K98c::main();
		break;
	case 3:
		character\wehrmacht_soldier_K98d::main();
		break;
	case 4:
		character\wehrmacht_soldier_K98e::main();
		break;
	}
}

precache()
{
	character\wehrmacht_soldier_K98a::precache();
	character\wehrmacht_soldier_K98b::precache();
	character\wehrmacht_soldier_K98c::precache();
	character\wehrmacht_soldier_K98d::precache();
	character\wehrmacht_soldier_K98e::precache();

	precacheItem("kar98k");
	precacheItem("Stielhandgranate");
}
